/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/sysinit.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/WSCDApi.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/system.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/lnfodwrf.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/exeinfo.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/strings.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/objpas.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/cthreads.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/sysutils.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/WscdApiServer.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/baseunix.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/unix.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/unixtype.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/initc.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/sysctl.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/unixutil.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/ctypes.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/errors.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/sysconst.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.base.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.os.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.text.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.unicode.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.rest.core.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.rest.http.server.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.rest.server.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.rest.sqlite3.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.db.raw.sqlite3.static.o
../../static/aarch64-darwin/sqlite3.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/Agenda.repository.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/Agenda.controller.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/Recibo.repository.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/Recibo.controller.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl-objpas/variants.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/classes.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/fcl-base/contnrs.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/types.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/rtlconsts.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/typinfo.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/math.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl-objpas/varutils.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/unixcp.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/termio.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl/dl.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.buffers.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.datetime.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.variants.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.data.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.rtti.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.json.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.fmt.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.threads.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.perf.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.crypt.core.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.crypt.secure.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.crypt.jwt.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.log.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.interfaces.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.orm.base.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.orm.core.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.soa.core.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.db.core.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.os.security.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/fcl-base/syncobjs.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.lib.static.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.search.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.lib.sspi.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.crypt.ecc256r1.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.crypt.ecc.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.crypt.rsa.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.zip.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.lib.z.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.core.collections.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.orm.rest.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.soa.server.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.rest.memserver.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.net.sock.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.net.http.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.net.server.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.net.async.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.net.ws.core.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.net.ws.server.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.net.ws.async.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.soa.client.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.rest.client.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.lib.gssapi.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.orm.client.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.orm.server.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.orm.storage.o
/Users/rafakwolf/lazarus_installation/fpc/units/aarch64-darwin/rtl-extra/sockets.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.net.client.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.orm.sqlite3.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/mormot.db.raw.sqlite3.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/Agenda.service.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/Recibo.service.o
/Users/rafakwolf/Developer/wscd/lib/aarch64-darwin/api/Extensos.o
