
/****************** GENERATORS ********************/

CREATE GENERATOR GENIDCONFIGURACAO;
CREATE GENERATOR GENIDITEMPERFIL;
CREATE GENERATOR GENIDLOGOPERACAO;
CREATE GENERATOR GENIDLOG_AGENDA;
CREATE GENERATOR GENIDLOG_ALIQUOTAS;
CREATE GENERATOR GENIDMENSAGEM;

/******************* PROCEDURES ******************/

SET TERM ^ ;
CREATE PROCEDURE STPABRELOGOPERACAO (
    ORIGEM Varchar(80),
    USUARIO Varchar(10) )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPBAIXACOMPRA (
    CODIGO Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPBAIXAVENDA (
    CODIGO Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPCAIXASPADRAO (
    ID Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPCONFIGPADRAO (
    COMPUTADOR Varchar(80),
    DIREXP Varchar(150) )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPDELCAIXA (
    CODIGO Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPDELCP (
    CODIGO Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPDELCR (
    CODIGO Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPDELDUPLICATA (
    CODIGO Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPDELETQPRODUTO (
    CODIGO Varchar(13) )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPDELORCAMENTO (
    CODIGO Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPDELVENDA (
    CODIGO Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPDESMARCAPROMOCAO
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPESTORNACOMPRA (
    CODIGO Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPESTORNAVENDA (
    CODIGO Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPFECHALOGOPERACAO
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPGETCLIENTEANIVER (
    TIPO Integer,
    DIAINI Integer,
    DIAFIM Integer,
    MES Integer,
    ANO Integer,
    DATA1 Date,
    DATA2 Date )
RETURNS (
    NOME Varchar(50),
    DATANASC Date,
    ENDERECO Varchar(50),
    CIDADE Varchar(50),
    BAIRRO Varchar(50),
    CEP Varchar(20),
    FONE Varchar(20) )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPGETID (
    FIELDNAME Varchar(31),
    TABLENAME Varchar(31) )
RETURNS (
    ID Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPINSCAIXA (
    CONTA Integer,
    DATA Date,
    DESCRICAO Varchar(80),
    DOCUMENTO Varchar(20),
    TIPO Char(1),
    VALOR Numeric(13,4) )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPINSCHEQUE (
    PIDBANCO Integer,
    PIDCLIENTE Integer,
    PIDFORN Integer,
    PBANDAMAGNETICA Varchar(35),
    PAGENCIA Varchar(20),
    PCONTA Varchar(20),
    PNUMERO Varchar(20),
    PDATAEMISSAO Date,
    PBOMPARA Date,
    PVALOR Numeric(13,4),
    PVENDA Integer,
    PCOMPRA Integer,
    PREPASSADO Char(1),
    PDATABAIXADO Date )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPPAGTOCOMPRA (
    IDCOMPRA Integer,
    DATAPAGTO Date,
    FORMAPAGTO Varchar(20),
    VALORPAGO Numeric(13,2) )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPPRODUTOSVENCIDOS (
    DATAVENC Date,
    IDUN Integer,
    IDGRUPO Integer,
    IDFORNECEDOR Integer )
RETURNS (
    CODBARRA Varchar(13),
    PRODUTO Varchar(50),
    DATAVENCIMENTO Date,
    UNIDADE Varchar(20),
    GRUPO Varchar(50),
    FORNECEDOR Varchar(50),
    PRECOCUSTO Numeric(13,2) )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPRECTOVENDA (
    IDVENDA Integer,
    DATARECTO Date,
    FORMARECTO Varchar(20),
    VALORRECDO Numeric(13,2) )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPRELCAIXAMESANO (
    MES Integer,
    ANO Integer,
    PORDEM Char(1) )
RETURNS (
    CODIGO Integer,
    DATA Date,
    DESCRICAO Varchar(80),
    DOCUMENTO Varchar(20),
    TIPO Char(1),
    VALOR Numeric(13,2),
    TOTALCREDITOS Numeric(13,2),
    TOTALDEBITOS Numeric(13,2),
    TOTALSALDO Numeric(13,2),
    TOTAL Numeric(13,2) )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPRELCAIXATIPOCONTA (
    PDATAINI Date,
    PDATAFIM Date,
    PTIPOCONTA Char(1),
    PORDEM Char(1) )
RETURNS (
    CODIGO Integer,
    TOTAL Numeric(13,2),
    DATA Date,
    DESCRICAO Varchar(80),
    DOCUMENTO Varchar(20),
    TIPO Char(1),
    VALOR Numeric(13,2) )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPRESTOCOMPRA (
    PIDCOMPRA Integer )
RETURNS (
    RESTO Numeric(13,2) )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPRESTOVENDA (
    PIDVENDA Integer )
RETURNS (
    RESTO Numeric(13,2) )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPSITUACAOCLIENTE (
    CODIGO Integer )
RETURNS (
    CLIENTE Varchar(80),
    LIMITECLIENTE Numeric(13,2),
    DATACADASTRO Date,
    TOTALCONTAS Numeric(13,2),
    TOTALCONTASVENCIDAS Numeric(13,2),
    PRIMEIROVENCIMENTO Date,
    DIASATRASO Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE STPVENDACOMISSAO (
    VENDEDOR Integer,
    DATAINI Date,
    DATAFIM Date )
RETURNS (
    CODPRODUTO Integer,
    DESCRICAO Varchar(150),
    QTD Integer,
    TOTAL Numeric(13,2),
    COMISSAO Numeric(13,2) )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

/******************** TABLES **********************/

CREATE TABLE AGENDA
(
  IDAGENDA Integer NOT NULL,
  NOME Varchar(80),
  TELEFONE Varchar(20),
  TELEFONE2 Varchar(20),
  TELEFONE3 Varchar(20),
  FAX Varchar(20),
  OBS Blob sub_type 1,
  CONSTRAINT PK_AGENDA PRIMARY KEY (IDAGENDA)
);
CREATE TABLE ALIQUOTAS
(
  CODALIQUOTA Integer NOT NULL,
  DESCRICAO Varchar(20),
  CONSTRAINT PK_ALIQUOTAS PRIMARY KEY (CODALIQUOTA)
);
CREATE TABLE BANCO
(
  IDBANCO Integer NOT NULL,
  BANCO Varchar(80),
  CONSTRAINT PK_BANCO PRIMARY KEY (IDBANCO)
);
CREATE TABLE CAIXA
(
  CODCAIXA Integer NOT NULL,
  CODCAIXAS Integer NOT NULL,
  DATA Date,
  DESCRICAO Varchar(80),
  DOCUMENTO Varchar(20),
  TIPO Char(1) CHECK (TIPO IN ('C', 'D')),
  VALOR Numeric(13,4),
  EXCLUIR Char(1) CHECK (EXCLUIR IN ('S', 'N') OR EXCLUIR IS NULL),
  CONSTRAINT PK_CAIXA PRIMARY KEY (CODCAIXA)
);
CREATE TABLE CAIXAS
(
  CODIGO Integer NOT NULL,
  NOME Varchar(80),
  INATIVO Char(1) CHECK (INATIVO IN ('S', 'N') OR INATIVO IS NULL),
  CONSTRAINT PK_CAIXAS PRIMARY KEY (CODIGO)
);
CREATE TABLE CFOP
(
  NUMERO Varchar(20) NOT NULL,
  OPERACAO Varchar(250),
  CFNOTA Varchar(1000),
  CONSTRAINT PK_CFOP PRIMARY KEY (NUMERO)
);
CREATE TABLE CHEQUE
(
  IDCHEQUE Integer NOT NULL,
  IDBANCO Integer,
  IDCLIENTE Integer,
  IDFORN Integer,
  BANDAMAGNETICA Varchar(35),
  AGENCIA Varchar(80),
  CONTA Varchar(20),
  NUMERO Varchar(20),
  DATAEMISSAO Date,
  BOMPARA Date,
  VALOR Numeric(13,4),
  VENDA Integer,
  COMPRA Integer,
  REPASSADO Char(1) CHECK (REPASSADO IN ('S', 'N') OR REPASSADO IS NULL),
  DATABAIXADO Date,
  CONSTRAINT PK_CHEQUE PRIMARY KEY (IDCHEQUE)
);
CREATE TABLE CIDADES
(
  CODCIDADE Integer NOT NULL,
  DESCRICAO Varchar(80),
  CONSTRAINT PK_CIDADES PRIMARY KEY (CODCIDADE)
);
CREATE TABLE CLIENTES
(
  CODCLIENTE Integer NOT NULL,
  TIPO Char(1),
  NOME Varchar(80),
  ENDERECO Varchar(80),
  CEP Varchar(10),
  BAIRRO Varchar(80),
  TELEFONE Varchar(20),
  FAX Varchar(20),
  CODCIDADE Integer,
  UF Char(2),
  TEMPO_MORADIA Varchar(80),
  END_ANTERIOR Varchar(80),
  E_MAIL Varchar(80),
  TRABALHO Varchar(80),
  CARGO Varchar(80),
  DATA_INICIO Date,
  SALARIO Numeric(13,4),
  ESTADO_CIVIL Char(1),
  CONJUGUE Varchar(80),
  LOCAL_TRAB Varchar(80),
  DATA_NASC Date,
  PAI Varchar(80),
  MAE Varchar(80),
  CPF_CNPJ Varchar(20),
  RG_IE Varchar(20),
  REFER_PES Varchar(250),
  REFER_COM Varchar(250),
  FONE_COM Varchar(20),
  CADASTRO Date,
  OBS Blob sub_type 1,
  NATURALIDADE Varchar(80),
  LIMITE Numeric(13,4),
  FOTO Blob sub_type 0,
  CONSTRAINT PK_CLIENTES PRIMARY KEY (CODCLIENTE)
);
CREATE TABLE CONFIGDUPLICATA
(
  CAMPO Varchar(80),
  VERTICAL Integer,
  HORIZONTAL Integer,
  FONTE Integer,
  NOMECAMPO Varchar(80),
  TIPOFONTE Varchar(80),
  ESTILOFONTE Varchar(80)
);
CREATE TABLE CONFIGNOTA
(
  CODIGO Integer NOT NULL,
  CAMPO Varchar(80),
  LAYOUT Varchar(80),
  REFERENCIA Varchar(80),
  TIPO Char(1),
  LINHA Integer,
  COLUNA Integer,
  IMPRIMIR Char(1) CHECK (IMPRIMIR IN ('S', 'N') OR IMPRIMIR IS NULL),
  CONSTRAINT PK_CONFIGNOTA PRIMARY KEY (CODIGO)
);
CREATE TABLE CONFIGURACAO
(
  IDCONFIGURACAO Integer NOT NULL,
  NOMECOMPUTADOR Varchar(80),
  BARRAFERRAMENTA Char(1) CHECK (BARRAFERRAMENTA IN ('S', 'N') OR BARRAFERRAMENTA IS NULL),
  HINTBALAO Char(1) CHECK (HINTBALAO IN ('S', 'N') OR HINTBALAO IS NULL),
  GRAVAERRO Char(1) CHECK (GRAVAERRO IN ('S', 'N') OR GRAVAERRO IS NULL),
  BACKUP Char(1) CHECK (BACKUP IN ('S', 'N') OR BACKUP IS NULL),
  LOG Char(1) CHECK (LOG IN ('S', 'N') OR LOG IS NULL),
  IMPRESSORA Char(1) CHECK (IMPRESSORA IN ('S', 'N') OR IMPRESSORA IS NULL),
  RESOLUCAO Char(1) CHECK (RESOLUCAO IN ('S', 'N') OR RESOLUCAO IS NULL),
  LETRACODIGOBARRA Char(1) CHECK (LETRACODIGOBARRA IN ('S', 'N') OR LETRACODIGOBARRA IS NULL),
  EXIBEDICADIA Char(1) CHECK (EXIBEDICADIA IN ('S', 'N') OR EXIBEDICADIA IS NULL),
  AVISACLIENTEATRASO Char(1) CHECK (AVISACLIENTEATRASO IN ('S', 'N') OR AVISACLIENTEATRASO IS NULL),
  DIREXPORTPADRAO Varchar(250),
  SENHAESTOQUE Varchar(10),
  USARSENHAESTOQUE Char(1) CHECK (USARSENHAESTOQUE IN ('S', 'N') OR USARSENHAESTOQUE IS NULL),
  ESTOQUEPADRAO Integer,
  BORDAETQPROD Char(1) CHECK (BORDAETQPROD IN ('S', 'N') OR BORDAETQPROD IS NULL),
  ALIQUOTAPADRAO Integer NOT NULL,
  DESCPADRAOPROD Numeric(13,4),
  CAIXAPADRAO Integer NOT NULL,
  SENHACAIXA Varchar(10),
  PRODSEMESTOQORCAM Char(1) CHECK (PRODSEMESTOQORCAM IN ('S', 'N') OR PRODSEMESTOQORCAM IS NULL),
  ORCAMNAOCONC Char(1) CHECK (ORCAMNAOCONC IN ('S', 'N') OR ORCAMNAOCONC IS NULL),
  EDITORCAMCONC Char(1) CHECK (EDITORCAMCONC IN ('S', 'N') OR EDITORCAMCONC IS NULL),
  COMPRANAOCONC Char(1) CHECK (COMPRANAOCONC IN ('S', 'N') OR COMPRANAOCONC IS NULL),
  EDITCOMPRACONC Char(1) CHECK (EDITCOMPRACONC IN ('S', 'N') OR EDITCOMPRACONC IS NULL),
  PRODSEMESTOQVENDA Char(1) CHECK (PRODSEMESTOQVENDA IN ('S', 'N') OR PRODSEMESTOQVENDA IS NULL),
  VENDANAOCONC Char(1) CHECK (VENDANAOCONC IN ('S', 'N') OR VENDANAOCONC IS NULL),
  EDITVENDACONC Char(1) CHECK (EDITVENDACONC IN ('S', 'N') OR EDITVENDACONC IS NULL),
  BORDAETQCLIENTE Char(1) CHECK (BORDAETQCLIENTE IN ('S', 'N') OR BORDAETQCLIENTE IS NULL),
  MOSTRARSALDOCAIXA Char(1) CHECK (MOSTRARSALDOCAIXA IN ('S', 'N') OR MOSTRARSALDOCAIXA IS NULL),
  CAIXA90DIAS Char(1) CHECK (CAIXA90DIAS IN ('S', 'N') OR CAIXA90DIAS IS NULL),
  RELZEBRADO Char(1) CHECK (RELZEBRADO IN ('S', 'N') OR RELZEBRADO IS NULL),
  VERIFICA_UPD Char(1) CHECK (VERIFICA_UPD IN ('S', 'N') OR VERIFICA_UPD IS NULL),
  CONTACHEQUE Integer,
  INFOAVISOS Char(1) CHECK (INFOAVISOS IN ('S', 'N') OR INFOAVISOS IS NULL),
  CONSTRAINT PK_CONFIGURACAO PRIMARY KEY (IDCONFIGURACAO)
);
CREATE TABLE CONFIGURACAOGLOBAL
(
  TAXAJURO Numeric(13,4),
  INTERVALO Integer,
  PRAZOINICIAL Integer,
  PARCELAS Integer,
  LIMITECLIENTE Numeric(13,4),
  TITULOORCAM Varchar(80),
  COLUNAORCAMBOBINA Integer,
  MSGRODAPEORCAM Varchar(250),
  TITULOVENDA Varchar(80),
  COLUNAVENDABOBINA Integer,
  MSGRODAPEVENDA Varchar(250),
  LINHAPULARBOBINAVENDA Integer,
  LINHAPULARBOBINAORCAM Integer,
  PORTAIMPVENDA Varchar(20),
  FTP_HOST Varchar(80),
  FTP_USER_NAME Varchar(80),
  FTP_PASSWORD Varchar(80),
  FTP_TIMEOUT Integer,
  FTP_PASSIVE Char(1) CHECK (FTP_PASSIVE IN ('S', 'N') OR FTP_PASSIVE IS NULL),
  FTP_DIR Varchar(80),
  IDADECADASTROCLIENTE Integer,
  IDCONFIGGLOBAL Integer NOT NULL,
  CONSTRAINT PK_CONFIGURACAOGLOBAL PRIMARY KEY (IDCONFIGGLOBAL)
);
CREATE TABLE CONTASPAGAR
(
  CODIGO Integer NOT NULL,
  DATA Date,
  VENCIMENTO Date,
  DESCRICAO Varchar(80),
  FORNECEDOR Integer,
  VALOR Numeric(13,4),
  DOCUMENTO Varchar(20),
  PAGAR Char(1) CHECK (PAGAR IN ('S', 'N') OR PAGAR IS NULL),
  JURO Numeric(13,4),
  PAGA Char(1) CHECK (PAGA IN ('S', 'N') OR PAGA IS NULL),
  DATAPAGTO Date,
  ORIGEM Integer,
  COMPRA Integer,
  CAPITALPAGO Numeric(13,4),
  JUROPAGO Numeric(13,4),
  DESCTO Numeric(13,4),
  OBS Blob sub_type 1,
  IDCONTA Integer,
  CONSTRAINT PK_CONTASPAGAR PRIMARY KEY (CODIGO)
);
CREATE TABLE CONTASRECEBER
(
  CODIGO Integer NOT NULL,
  DATA Date,
  VENCIMENTO Date,
  CLIENTE Integer,
  DESCRICAO Varchar(80),
  DOCUMENTO Varchar(20),
  VALOR Numeric(13,4),
  JURO Numeric(13,4),
  RECEBER Char(1) CHECK (RECEBER IN ('S', 'N') OR RECEBER IS NULL),
  RECDA Char(1) CHECK (RECDA IN ('S', 'N') OR RECDA IS NULL),
  DATARECTO Date,
  ORIGEM Integer,
  VENDA Integer,
  CAPITALRECDO Numeric(13,4),
  JURORECDO Numeric(13,4),
  DESCTO Numeric(13,4),
  OBS Blob sub_type 1,
  IDCONTA Integer,
  CONSTRAINT PK_CONTASRECEBER PRIMARY KEY (CODIGO)
);
CREATE TABLE DUPLICATA
(
  IDDUPLICATA Integer NOT NULL,
  NRODUPLICATA Varchar(20),
  SACADO Varchar(80),
  CPF_CNPJ Varchar(20),
  ENDERECO Varchar(80),
  BAIRRO Varchar(80),
  CEP Varchar(10),
  IDCIDADE Integer,
  FONEFAX Varchar(20),
  UF Char(2),
  IE Varchar(20),
  DATAEMISSAO Date,
  NROFATURA Varchar(20),
  VALOR_FATURA Numeric(13,4),
  VALOR Numeric(13,4),
  DATAVENC Date,
  DESCONTO Numeric(13,4),
  PRACAPAGAMENTO Varchar(250),
  DATADESCTO Date,
  VALOREXTENSO Varchar(250),
  DATAIMPRESSAO Date,
  IMPRESSA Char(1) CHECK (IMPRESSA IN ('S', 'N') OR IMPRESSA IS NULL),
  CONSTRAINT PK_DUPLICATA PRIMARY KEY (IDDUPLICATA)
);
CREATE TABLE EMPRESA
(
  FANTAZIA Varchar(80),
  RAZASOCIAL Varchar(80),
  CNPJ Varchar(20),
  IE Varchar(20),
  IM Varchar(20),
  ENDERECO Varchar(80),
  IDCIDADE Integer,
  BAIRRO Varchar(80),
  CEP Varchar(10),
  TELEFONE Varchar(20),
  FAX Varchar(20),
  UF Char(2),
  RESPONSAVEL Varchar(80),
  LOGOEMPRESA Blob sub_type 0,
  EMAIL Varchar(250)
);
CREATE TABLE ENVELOPE
(
  IDENVELOPE Integer NOT NULL,
  NOME Varchar(80),
  ENDERECO Varchar(80),
  IDCIDADE Integer,
  BAIRRO Varchar(80),
  CEP Varchar(10),
  MENSAGEM Varchar(250),
  CONSTRAINT PK_ENVELOPE PRIMARY KEY (IDENVELOPE)
);
CREATE TABLE ETIQUETA
(
  IDETIQUETA Integer NOT NULL,
  ETIQUETA Varchar(80),
  ALTURAFOLHA Float,
  LARGURAFOLHA Float,
  MARGEMSUPERIOR Float,
  MARGEMESQUERDA Float,
  NUMEROLINHAS Integer,
  NUMEROCOLUNAS Integer,
  ALTURAETIQUETA Float,
  LARGURAETIQUETA Float,
  DISTANCIAVERTICAL Float,
  DISTANCIAHORIZONTAL Float,
  DISTACOLVERTICAL Float,
  DISTCOLHORIZ Float,
  CONSTRAINT PK_ETIQUETA PRIMARY KEY (IDETIQUETA)
);
CREATE TABLE ETIQUETAPROD
(
  IDETIQUETAPROD Integer NOT NULL,
  CODBARRA Varchar(13),
  DESCRICAO Varchar(80),
  PRECO Numeric(13,4),
  CONSTRAINT PK_ETIQUETAPROD PRIMARY KEY (IDETIQUETAPROD)
);
CREATE TABLE FORNECEDORES
(
  CODFORNECEDOR Integer NOT NULL,
  FANTAZIA Varchar(80),
  RAZAOSOCIAL Varchar(80),
  DATACAD Date,
  ENDERECO Varchar(80),
  CIDADE Integer,
  BAIRRO Varchar(80),
  CNPJ Varchar(20),
  IE Varchar(20),
  CEP Varchar(10),
  TELEFONE Varchar(20),
  FAX Varchar(20),
  EMAIL Varchar(80),
  UF Char(2),
  OBS Blob sub_type 1,
  VENDEDOR Varchar(80),
  TELEFONEVENDEDOR Varchar(20),
  EMAILVENDEDOR Varchar(80),
  TIPO Char(1),
  CONSTRAINT PK_FORNECEDORES PRIMARY KEY (CODFORNECEDOR)
);
CREATE TABLE GRUPOS
(
  CODGRUPO Integer NOT NULL,
  DESCRICAO Varchar(80),
  CONSTRAINT PK_GRUPOS PRIMARY KEY (CODGRUPO)
);
CREATE TABLE ITEMNOTAFISCAL
(
  NUMERO Integer NOT NULL,
  PRODUTO Integer,
  ALIQUOTA Integer,
  QTDE Integer,
  TOTAL Numeric(13,4),
  CUSTO Numeric(13,4),
  LUCRO Integer,
  VENDA Numeric(13,4),
  IPI Numeric(13,4),
  DESCONTO Numeric(13,4)
);
CREATE TABLE ITEMORCAMENTO
(
  CODIGO Integer NOT NULL,
  CODPRODUTO Integer,
  QTDE Integer,
  CUSTO Numeric(13,4),
  VENDA Numeric(13,4),
  DESCTO Numeric(13,4),
  VALORDESCTO Numeric(13,4),
  TOTAL Numeric(13,4)
);
CREATE TABLE ITEMPERFIL
(
  IDITEMPERFIL Integer NOT NULL,
  IDPERFIL Integer NOT NULL,
  ACAO_NOME Varchar(80),
  ACAO_CAPTION Varchar(80),
  LIBERADO Char(1) CHECK (LIBERADO IN ('S', 'N') OR LIBERADO IS NULL),
  CONSTRAINT PK_ITEMPERFIL PRIMARY KEY (IDITEMPERFIL)
);
CREATE TABLE ITEMVENDA
(
  CODIGO Integer NOT NULL,
  CODPRODUTO Integer,
  QTD Integer,
  CUSTO Numeric(13,4),
  VENDA Numeric(13,4),
  DESCTO Numeric(13,4),
  VALORDESCTO Numeric(13,4),
  TOTAL Numeric(13,4),
  COMISSAO Numeric(13,4),
  VALORCOMISSAO Numeric(13,4)
);
CREATE TABLE LOGERRO
(
  IDLOGERRO Integer NOT NULL,
  DATAHORA Timestamp,
  FORM Varchar(80),
  CONTROLE Varchar(80),
  MSG Varchar(250),
  CONSTRAINT PK_LOGERRO PRIMARY KEY (IDLOGERRO)
);
CREATE TABLE LOGOPERACAO
(
  IDLOGOPERACAO Integer NOT NULL,
  IDCONNECTION Integer,
  ORIGEM Varchar(80),
  USUARIO Varchar(10),
  DATAHORA Timestamp,
  ABERTO Integer CHECK (ABERTO IN (0, 1) OR ABERTO IS NULL),
  CONSTRAINT PK_LOGOPERACAO PRIMARY KEY (IDLOGOPERACAO)
);
CREATE TABLE LOG_AGENDA
(
  IDLOG_AGENDA Integer NOT NULL,
  TIPOOPERACAO Char(1),
  USUARIO Varchar(10),
  DATAHORA Timestamp,
  IDLOGOPERACAO Integer,
  IDAGENDA Integer,
  NOME Varchar(80),
  TELEFONE Varchar(20),
  FAX Varchar(20),
  CONSTRAINT PK_LOG_AGENDA PRIMARY KEY (IDLOG_AGENDA)
);
CREATE TABLE LOG_ALIQUOTAS
(
  IDLOG_ALIQUOTAS Integer NOT NULL,
  TIPOOPERACAO Char(1),
  USUARIO Varchar(10),
  DATAHORA Timestamp,
  IDLOGOPERACAO Integer,
  CODALIQUOTA Integer,
  DESCRICAO Varchar(20),
  CONSTRAINT PK_LOG_ALIQUOTAS PRIMARY KEY (IDLOG_ALIQUOTAS)
);
CREATE TABLE MENSAGEM
(
  IDMENSAGEM Integer NOT NULL,
  MENSAGEM Varchar(255),
  DATA_CADASTRO Date,
  TIPO Char(1),
  IDWEB Integer,
  CONSTRAINT PK_MENSAGEM PRIMARY KEY (IDMENSAGEM)
);
CREATE TABLE NOTAS_FISCAIS
(
  NUMERO Integer NOT NULL,
  CODFORNECEDOR Integer,
  DATANOTA Date,
  DATAENTRADA Date,
  CFOP Varchar(20),
  DESCONTO Numeric(13,4),
  ICMS Numeric(13,4),
  IPI Numeric(13,4),
  FRETE Numeric(13,4),
  DESPESAS Numeric(13,4),
  TOTALPRODUTO Numeric(13,4),
  TOTAL Numeric(13,4),
  OBS Blob sub_type 1,
  BAIXADO Char(1) CHECK (BAIXADO IN ('S', 'N') OR BAIXADO IS NULL),
  CONCLUIDA Char(1) CHECK (CONCLUIDA IN ('S', 'N') OR CONCLUIDA IS NULL),
  CANCELADO Char(1) CHECK (CANCELADO IN ('S', 'N') OR CANCELADO IS NULL),
  CONSTRAINT PK_NOTAS_FISCAIS PRIMARY KEY (NUMERO)
);
CREATE TABLE ORCAMENTO
(
  CODIGO Integer NOT NULL,
  IDVENDEDOR Integer,
  CODCLIENTE Integer,
  DATA Date,
  OBS Varchar(250),
  TOTAL Numeric(13,4),
  ITENS Integer,
  STATUS Char(1),
  CONCLUIDO Char(1) CHECK (CONCLUIDO IN ('S', 'N') OR CONCLUIDO IS NULL),
  CONSTRAINT PK_ORCAMENTO PRIMARY KEY (CODIGO)
);
CREATE TABLE PAGTOCOMPRA
(
  IDPAGTOCOMPRA Integer NOT NULL,
  IDCOMPRA Integer,
  DATAPAGTO Date,
  FORMAPAGTO Varchar(20),
  VALORPAGO Numeric(13,4),
  VALORRESTO Numeric(13,4),
  CONSTRAINT PK_PAGTOCOMPRA PRIMARY KEY (IDPAGTOCOMPRA)
);
CREATE TABLE PERDA
(
  CODIGO Integer NOT NULL,
  CODPRODUTO Integer,
  QTDE Integer,
  PRECO Numeric(13,4),
  DATA Date,
  MOTIVO Char(1),
  OBS Blob sub_type 1,
  CONSTRAINT PK_PERDA PRIMARY KEY (CODIGO)
);
CREATE TABLE PERFIL
(
  IDPERFIL Integer NOT NULL,
  PERFIL Varchar(80),
  CONSTRAINT PK_PERFIL PRIMARY KEY (IDPERFIL)
);
CREATE TABLE PRODUTOS
(
  IDPRODUTO Integer NOT NULL,
  CODBARRA Varchar(13),
  REFERENCIA Varchar(20),
  CODFORNECEDOR Integer,
  CODGRUPO Integer,
  DESCRICAO Varchar(80),
  ABREVIACAO Varchar(80),
  DATAVALIDADE Date,
  CODUNIDADE Integer,
  PESO Numeric(13,4),
  PRECO_PROMOCAO Numeric(13,4),
  CUSTO Numeric(13,4),
  LUCRO Numeric(13,4),
  VENDA Numeric(13,4),
  ESTOQUE Integer,
  ESTOQUEMINIMO Integer,
  IDALIQUOTA Integer,
  NOVO Integer CHECK (NOVO IN (0, 1) OR NOVO IS NULL),
  ALTERADO Integer CHECK (ALTERADO IN (0, 1) OR ALTERADO IS NULL),
  QTDERECEBIDA Integer,
  DATARECEBIDA Date,
  EXCLUIR Char(1) CHECK (EXCLUIR IN ('S', 'N') OR EXCLUIR IS NULL),
  PROMOCAO Char(1) CHECK (PROMOCAO IN ('S', 'N') OR PROMOCAO IS NULL),
  OBS Blob sub_type 1,
  CONSTRAINT PK_PRODUTOS PRIMARY KEY (IDPRODUTO)
);
CREATE TABLE PROMOCAO
(
  CODIGO Integer NOT NULL,
  PRODUTO Integer NOT NULL,
  DESCONTO Numeric(13,4),
  PRECO Numeric(13,4),
  INICIO Date,
  FIM Date,
  CONSTRAINT PK_PROMOCAO PRIMARY KEY (CODIGO),
  CONSTRAINT UN_PROMOCAO_PRODUTO UNIQUE (PRODUTO)
);
CREATE TABLE RECIBO
(
  IDRECIBO Integer NOT NULL,
  DATA Date,
  RECEBEDOR Varchar(250),
  REFERENTE Blob sub_type 1,
  VALOR Numeric(13,4),
  VALOREXTENSO Blob sub_type 1,
  CONSTRAINT PK_RECIBO PRIMARY KEY (IDRECIBO)
);
CREATE TABLE RECTOVENDA
(
  IDRECTOVENDA Integer NOT NULL,
  IDVENDA Integer,
  DATARECTO Date,
  FORMARECTO Varchar(20),
  VALORRECDO Numeric(13,4),
  VALORRESTO Numeric(13,4),
  CONSTRAINT PK_RECTOVENDA PRIMARY KEY (IDRECTOVENDA)
);
CREATE TABLE SISTEMA
(
  IDSISTEMA Integer DEFAULT 1 NOT NULL,
  VERSAO Varchar(20),
  DATAVALIDADE Varchar(10),
  DATA_ACESSO Varchar(10),
  SERIAL Varchar(20),
  HD Varchar(20),
  CONSTRAINT PK_SISTEMA PRIMARY KEY (IDSISTEMA)
);
CREATE TABLE UNIDADES
(
  CODUNIDADE Integer NOT NULL,
  DESCRICAO Varchar(20),
  CONSTRAINT PK_UNIDADES PRIMARY KEY (CODUNIDADE)
);
CREATE TABLE USUARIOS
(
  IDUSUARIOS Integer NOT NULL,
  NOME Varchar(80),
  LOGIN Varchar(10) NOT NULL,
  SENHA Varchar(10),
  IDPERFIL Integer,
  CONSTRAINT PK_USUARIOS PRIMARY KEY (IDUSUARIOS)
);
CREATE TABLE VENDA
(
  CODIGO Integer NOT NULL,
  IDVENDEDOR Integer,
  CODCLIENTE Integer,
  DATA Date,
  OBS Varchar(250),
  TOTALDESCTO Numeric(13,4),
  TOTAL Numeric(13,4),
  CONCLUIDA Char(1) CHECK (CONCLUIDA IN ('S', 'N') OR CONCLUIDA IS NULL),
  BAIXADO Char(1) CHECK (BAIXADO IN ('S', 'N') OR BAIXADO IS NULL),
  CANCELADO Char(1) CHECK (CANCELADO IN ('S', 'N') OR CANCELADO IS NULL),
  CONSTRAINT PK_VENDA PRIMARY KEY (CODIGO)
);
CREATE TABLE VENDEDOR
(
  IDVENDEDOR Integer NOT NULL,
  VENDEDOR Varchar(80),
  ATIVO Char(1) CHECK (ATIVO IN ('S', 'N') OR ATIVO IS NULL),
  CONSTRAINT PK_VENDEDOR PRIMARY KEY (IDVENDEDOR)
);
/********************* VIEWS **********************/

CREATE VIEW VIEWAGENDA (NOME, TELEFONE, TELEFONE2, TELEFONE3, FAX)
AS 
select
    AG.NOME,
    AG.TELEFONE,
    AG.TELEFONE2,
    AG.TELEFONE3,
    AG.FAX
  from AGENDA AG;
CREATE VIEW VIEWCAIXA (CODIGO, CONTA_CAIXA, DATA, HISTORICO, DOCUMENTO, TIPO, VALOR)
AS 
SELECT
    C.CODCAIXA, 
    CS.NOME,
    C.DATA,
    C.DESCRICAO,
    C.DOCUMENTO,
    C.TIPO,
    C.VALOR
  FROM CAIXA C
  LEFT JOIN CAIXAS CS ON (CS.CODIGO = C.CODCAIXAS)
;
CREATE VIEW VIEWCAIXAS (IDCAIXAS, CAIXANOME, INATIVO)
AS 
select
    CODIGO,
    NOME,
    INATIVO
from CAIXAS
;
CREATE VIEW VIEWCAIXASATIVOS (CODIGO, NOME)
AS 
SELECT
    CS.CODIGO,
    CS.NOME
  FROM CAIXAS CS
  WHERE CS.INATIVO <> 'S'
;
CREATE VIEW VIEWCHEQUE (CODIGO, BANCO, NOME, BANDAMAGNETICA, AGENCIA, CONTA, NUMERO, DATAEMISSAO, BOMPARA, VALOR)
AS 
SELECT
    CQ.IDCHEQUE, 
    B.BANCO,
    CASE WHEN CQ.REPASSADO = 'S' THEN
      F.RAZAOSOCIAL
    ELSE
      C.NOME
    END,
    CQ.BANDAMAGNETICA,
    CQ.AGENCIA,
    CQ.CONTA,
    CQ.NUMERO,
    CQ.DATAEMISSAO,
    CQ.BOMPARA,
    CQ.VALOR
FROM CHEQUE CQ
LEFT JOIN BANCO B ON (B.IDBANCO = CQ.IDBANCO)
LEFT JOIN CLIENTES C ON (C.CODCLIENTE = CQ.IDCLIENTE)
LEFT JOIN FORNECEDORES F ON (F.CODFORNECEDOR = CQ.IDFORN)
;
CREATE VIEW VIEWEMPRESA (RAZAOSOCIAL, CNPJ, IE, ENDERECO, CIDADE, BAIRRO, CEP, TELEFONE, FAX, UF, RESPONSAVEL, LOGOEMPRESA, EMAIL)
AS 
SELECT
      e.RAZASOCIAL,
      e.CNPJ,
      e.IE,
      e.ENDERECO,
      c.Descricao,
      e.BAIRRO,
      e.CEP,
      e.TELEFONE,
      e.FAX,
      e.UF,
      e.RESPONSAVEL,
      e.Logoempresa,
      e.EMAIL
    FROM EMPRESA e
    LEFT JOIN CIDADES c on (e.Idcidade = c.Codcidade)
;
CREATE VIEW VIEWENDERECOCLIENTES (CODIGO, NOME, DATA, ENDERECO, CODCIDADE, CIDADE, BAIRRO, CEP)
AS 
SELECT
    C.CODCLIENTE,
    C.NOME,
    C.DATA_NASC,
    C.ENDERECO,
    C.CODCIDADE,
    CD.DESCRICAO,
    C.BAIRRO,
    C.CEP
  FROM CLIENTES C
  LEFT JOIN CIDADES CD ON (CD.CODCIDADE = C.CODCIDADE);
CREATE VIEW VIEWETIQUETACLIENTE (IDCLIENTE, IDCIDADE, TITULO, TEXTO)
AS 
select
    cli.CODCLIENTE,
    cli.CODCIDADE,
    cli.NOME TITULO,
    cli.ENDERECO || ASCII_CHAR(13) ||
    cli.BAIRRO || ASCII_CHAR(13) ||
    cid.DESCRICAO || ASCII_CHAR(13) ||
    cli.CEP TEXTO
  from CLIENTES cli
  left join CIDADES cid on (cid.CODCIDADE = cli.CODCLIENTE)
;
CREATE VIEW VIEWFICHACLIENTE (CODIGO, TIPO, NOME, ENDERECO, CEP, BAIRRO, TELEFONE, FAX, CODCIDADE, CIDADE, ESTADO, TEMPO_MORADIA, ENDERECO_ANTERIOR, EMAIL, TRABALHO, CARGO, DATA_INICIO, SALARIO, LIMITE, ESTADO_CIVIL, CONJUGUE, LOCAL_TRABALHO, DATA_NASCIMENTO, PAI, MAE, CPF_CNPJ, RG_IE, REFER_PESSOAL, REFER_COMERCIAL, FONE_COMERCIAL, DATA_CADASTRO, NATURALIDADE)
AS 
SELECT
    CLI.CODCLIENTE,
    CLI.TIPO, 
    CLI.NOME, 
    CLI.ENDERECO,
    CLI.CEP,
    CLI.BAIRRO,
    CLI.TELEFONE,
    CLI.FAX,
    CID.CODCIDADE,
    CID.DESCRICAO,
    CLI.UF, 
    CLI.TEMPO_MORADIA,
    CLI.END_ANTERIOR,
    CLI.E_MAIL,
    CLI.TRABALHO,
    CLI.CARGO,
    CLI.DATA_INICIO,
    CLI.SALARIO,
    CLI.LIMITE,
    CLI.ESTADO_CIVIL,
    CLI.CONJUGUE,
    CLI.LOCAL_TRAB,
    CLI.DATA_NASC,
    CLI.PAI,
    CLI.MAE,
    CLI.CPF_CNPJ,
    CLI.RG_IE,
    CLI.REFER_PES,
    CLI.REFER_COM,
    CLI.FONE_COM,
    CLI.CADASTRO,
    CLI.NATURALIDADE
FROM CLIENTES CLI
LEFT JOIN CIDADES CID ON(CLI.CODCIDADE = CID.CODCIDADE)
;
CREATE VIEW VIEWFK (FK, TABELA)
AS 
select
  rrc.RDB$CONSTRAINT_NAME,
  rrc.RDB$RELATION_NAME
from RDB$RELATION_CONSTRAINTS rrc
where upper(rrc.RDB$CONSTRAINT_TYPE) = 'FOREIGN KEY'
;
CREATE VIEW VIEWFORNECEDORES (CODIGO, FANTASIA, RAZAO_SOCIAL, DATA_CADASTRO, ENDERECO, CIDADE, BAIRRO, CNPJ, IE, CEP, TELEFONE, FAX, EMAIL, UF, VENDEDOR, FONE_VENDEDOR, EMAIL_VENDEDOR)
AS 
  SELECT
    f.codfornecedor,
    f.fantazia,
    f.razaosocial,
    f.datacad,
    f.endereco,
    c.descricao,
    f.bairro, 
    f.cnpj,
    f.ie, 
    f.cep, 
    f.telefone,
    f.fax,
    f.email,
    f.uf, 
    f.vendedor,
    f.telefonevendedor,
    f.emailvendedor
  from fornecedores f
  left join cidades c on (f.cidade = c.codcidade)
;
CREATE VIEW VIEWITEMVENDA (CODVENDA, CODPRODUTO, PRODUTO, QTDE, DESCTO, PRECO, TOTAL)
AS 
  SELECT
    IV.CODIGO,
    IV.CODPRODUTO,
    PRO.DESCRICAO,
    ROUND(IV.QTD),
    IV.DESCTO,
    IV.VENDA,
    IV.TOTAL
  FROM ITEMVENDA IV
  LEFT JOIN PRODUTOS PRO ON (PRO.IDPRODUTO = IV.CODPRODUTO)
;
CREATE VIEW VIEWPERDAS (CODIGO, CODPRODUTO, PRODUTO, QUANTIDADE, PRECO, DATA, MOTIVO)
AS 
  SELECT
    PRD.CODIGO,
    PRD.CODPRODUTO,
    PROD.DESCRICAO,
    PRD.QTDE,
    PRD.PRECO,
    PRD.DATA,
    PRD.MOTIVO
  FROM PERDA PRD
  LEFT JOIN PRODUTOS PROD ON(PRD.CODPRODUTO = PROD.IDPRODUTO)
;
CREATE VIEW VIEWPESQUISAFONE (NOME, TELEFONE, FAX)
AS 
SELECT
    CAST(CLI.NOME AS VARCHAR(100)) NOME,
    CAST(CLI.TELEFONE AS VARCHAR(30)) TELEFONE,
    CAST(CLI.FAX AS VARCHAR(30)) FAX
  FROM CLIENTES CLI
  WHERE (CLI.TELEFONE <> '') OR (CLI.FAX <> '')

  UNION

  SELECT
    CAST(FORN.FANTAZIA AS VARCHAR(100)) NOME,
    CAST(FORN.TELEFONE AS VARCHAR(30)) TELEFONE,
    CAST(FORN.FAX AS VARCHAR(30))FAX
  FROM FORNECEDORES FORN
  WHERE (FORN.TELEFONE <> '') OR (FORN.FAX <> '')

  UNION

  SELECT
    CAST(AG.NOME AS VARCHAR(100)) NOME,
    CAST(AG.TELEFONE AS VARCHAR(30)) TELEFONE,
    CAST(AG.FAX AS VARCHAR(30)) FAX
  FROM AGENDA AG
  WHERE (AG.TELEFONE <> '') OR (AG.FAX <> '')
;
CREATE VIEW VIEWPESQUISAPRECO (CODIGO, CODIGOBARRA, REFERENCIA, DESCRICAO, ESTOQUE, PRECO, FORNECEDOR, GRUPO)
AS 
SELECT
    P.IDPRODUTO,
    P.CODBARRA,
    P.REFERENCIA,
    P.DESCRICAO,
    P.ESTOQUE,
    P.VENDA,
    F.FANTAZIA,
    G.DESCRICAO
  FROM PRODUTOS P
  LEFT JOIN FORNECEDORES F ON (P.CODFORNECEDOR = F.CODFORNECEDOR)
  LEFT JOIN GRUPOS G ON (P.CODGRUPO = G.CODGRUPO)
;
CREATE VIEW VIEWPK (PK, TABELA)
AS 
select
  rrc.RDB$CONSTRAINT_NAME,
  rrc.RDB$RELATION_NAME
from RDB$RELATION_CONSTRAINTS rrc
where upper(rrc.RDB$CONSTRAINT_TYPE) = 'PRIMARY KEY'
;
CREATE VIEW VIEWPRODUTOSMINIMOS (COD_BARRA, PRO_DESCRICAO, PRO_ESTOQUE, QTDE_MINIMA, CODFORNECEDOR, FORNECEDOR)
AS 
SELECT PROD.CODBARRA,
       PROD.DESCRICAO,
       PROD.ESTOQUE,
       PROD.ESTOQUEMINIMO,
       FRN.CODFORNECEDOR,
       FRN.FANTAZIA
FROM PRODUTOS PROD
LEFT JOIN FORNECEDORES FRN ON (FRN.CODFORNECEDOR =  PROD.CODFORNECEDOR)
WHERE (PROD.ESTOQUE <= PROD.ESTOQUEMINIMO)
;
CREATE VIEW VIEWRELCAIXA (CODIGO, DATA, DESCRICAO, DOCUMENTO, TIPO, VALOR)
AS 
  SELECT
     CX.CODCAIXA,
     CX.DATA,
     CX.DESCRICAO,
     CX.DOCUMENTO,
     CX.TIPO,
     CX.VALOR
  FROM CAIXA CX
;
CREATE VIEW VIEWRELCAIXACAIXAS (JAN, FEV, MAR, ABR, MAI, JUN, JUL, AGO, SEP, OUT, NOV, DEZ, NOME, SOMA)
AS 
  SELECT
      SUM(CASE WHEN EXTRACT(MONTH FROM CX.DATA) = 1 THEN CX.VALOR ELSE 0 END) JAN,
      SUM(CASE WHEN EXTRACT(MONTH FROM CX.DATA) = 2 THEN CX.VALOR ELSE 0 END) FEV,
      SUM(CASE WHEN EXTRACT(MONTH FROM CX.DATA) = 3 THEN CX.VALOR ELSE 0 END) MAR,
      SUM(CASE WHEN EXTRACT(MONTH FROM CX.DATA) = 4 THEN CX.VALOR ELSE 0 END) ABR,
      SUM(CASE WHEN EXTRACT(MONTH FROM CX.DATA) = 5 THEN CX.VALOR ELSE 0 END) MAI,
      SUM(CASE WHEN EXTRACT(MONTH FROM CX.DATA) = 6 THEN CX.VALOR ELSE 0 END) JUN,
      SUM(CASE WHEN EXTRACT(MONTH FROM CX.DATA) = 7 THEN CX.VALOR ELSE 0 END) JUL,
      SUM(CASE WHEN EXTRACT(MONTH FROM CX.DATA) = 8 THEN CX.VALOR ELSE 0 END) AGO,
      SUM(CASE WHEN EXTRACT(MONTH FROM CX.DATA) = 9 THEN CX.VALOR ELSE 0 END) SEP,
      SUM(CASE WHEN EXTRACT(MONTH FROM CX.DATA) = 10 THEN CX.VALOR ELSE 0 END) OUT,
      SUM(CASE WHEN EXTRACT(MONTH FROM CX.DATA) = 11 THEN CX.VALOR ELSE 0 END) NOV,
      SUM(CASE WHEN EXTRACT(MONTH FROM CX.DATA) = 12 THEN CX.VALOR ELSE 0 END) DEZ,
      SUM(CX.VALOR) SOMA,
      CXS.NOME
  FROM CAIXA CX
  LEFT JOIN CAIXAS CXS ON (CX.CODCAIXAS = CXS.CODIGO)
  GROUP BY CXS.NOME
;
CREATE VIEW VIEWRELCAIXATODOS (CODIGO, CAIXA, DATA, DESCRICAO, DOCUMENTO, TIPO, VALOR)
AS 
   SELECT
     CX.CODCAIXA,
     CXS.NOME,
     CX.DATA,
     CX.DESCRICAO,
     CX.DOCUMENTO,
     CX.TIPO,
     CX.VALOR
   FROM CAIXA CX
   LEFT JOIN CAIXAS CXS ON (CXS.CODIGO = CX.CODCAIXAS)
;
CREATE VIEW VIEWRELCLIENTES (CODIGO, NOME, ENDERECO, CPF_CNPJ, RG_IE, DATANASCIMENTO, CODCIDADE, CIDADE, TELEFONE, TIPO)
AS 
SELECT
    CLI.CODCLIENTE,
    CLI.NOME,
    CLI.ENDERECO,
    CLI.CPF_CNPJ,
    CLI.RG_IE,
    CLI.DATA_NASC,
    CID.CODCIDADE,
    CID.DESCRICAO,
    CLI.TELEFONE,
    CLI.TIPO
  FROM CLIENTES CLI
  INNER JOIN CIDADES CID ON(CLI.CODCIDADE = CID.CODCIDADE);
CREATE VIEW VIEWRELCP (CODIGO, DATA, VENCIMENTO, CODFORN, FORNECEDOR, DOCUMENTO, VALOR)
AS 
SELECT
    CP.Codigo,
    CP.DATA,
    CP.VENCIMENTO,
    CP.Fornecedor,
    FRN.FANTAZIA,
    CP.DOCUMENTO,
    CP.VALOR
  FROM CONTASPAGAR CP
  left JOIN FORNECEDORES FRN ON (FRN.Codfornecedor = CP.FORNECEDOR)
;
CREATE VIEW VIEWRELCPATRASADOS (CODIGO, DATA, VENCIMENTO, CODFORN, FORNECEDOR, DOCUMENTO, VALOR)
AS 
SELECT
    CP.Codigo,
    CP.DATA,
    CP.VENCIMENTO,
    CP.Fornecedor,
    FRN.FANTAZIA,
    CP.DOCUMENTO,
    CP.VALOR
  FROM CONTASPAGAR CP
  INNER JOIN FORNECEDORES FRN ON (FRN.Codfornecedor = CP.FORNECEDOR)
  WHERE CP.vencimento < current_date AND (CP.Paga = 'N')
;
CREATE VIEW VIEWRELCR (CODIGO, DATA, VENCIMENTO, CLIENTE, CAPITAL, TOTAL)
AS 
  SELECT
    CR.Codigo, 
    CR.DATA,
    CR.VENCIMENTO,
    CLI.NOME,
    CR.VALOR,
    CR.TOTAL
  FROM CONTASRECEBER CR
  LEFT JOIN CLIENTES CLI ON (CLI.Codcliente = CR.CLIENTE)
;
CREATE VIEW VIEWRELCRATRASADOS (CODIGO, VENCIMENTO, CODCLIENTE, CLIENTE, CAPITAL, DIASATRASO, TOTAL)
AS 
  SELECT
    CR.Codigo,
    CR.VENCIMENTO,
    CR.Cliente,
    CLI.Nome,
    CR.VALOR,
    CR.ATRASO,
    CR.TOTAL
  FROM CONTASRECEBER CR
  INNER JOIN CLIENTES CLI ON (CR.CLIENTE = CLI.CODCLIENTE)
  WHERE CR.VENCIMENTO < CURRENT_DATE AND (CR.Recda = 'N')
;
CREATE VIEW VIEWRELFORN (CODIGO, DATA, FANTAZIA, CNPJ, ENDERECO, CIDADE, TELEFONE)
AS 
SELECT
    FRN.CODFORNECEDOR,
    FRN.DATACAD,
    FRN.FANTAZIA,
    FRN.CNPJ,
    FRN.ENDERECO,
    cid.Descricao,
    FRN.TELEFONE
  FROM FORNECEDORES FRN
  left join CIDADES cid on (frn.Cidade = cid.Codcidade)
;
CREATE VIEW VIEWRELNPCR (CODIGO, DATA, VENCIMENTO, CODCLIENTE, CLIENTE, CAPITAL, TOTAL)
AS 
SELECT
    cr.CODIGO,
    cr.DATA,
    cr.VENCIMENTO,
    cr.CLIENTE,
    cli.NOME,
    cr.VALOR,
    cr.TOTAL
from CONTASRECEBER cr
left join CLIENTES cli on (CR.CLIENTE = cli.CODCLIENTE)
;
CREATE VIEW VIEWRELPRODUTOS (IDPRODUTO, CODBARRA, DESCRICAO, CODFORNECEDOR, FORNECEDOR, CODGRUPO, GRUPO, CUSTO, LUCRO, PRECO, ESTOQUE, VALORESTOQUE, NOVO, ALTERADO)
AS 
SELECT
    PROD.Idproduto,
    PROD.CODBARRA,
    PROD.DESCRICAO,
    prod.Codfornecedor,
    frn.Fantazia,
    prod.CODGRUPO,
    G.DESCRICAO,
    PROD.CUSTO,
    PROD.LUCRO,
    PROD.VENDA,
    PROD.ESTOQUE,
    PROD.VALOR_ESTOQUE,
    PROD.NOVO,
    PROD.ALTERADO
  FROM PRODUTOS PROD
  LEFT JOIN GRUPOS G ON(G.CODGRUPO = PROD.CODGRUPO)
  left join FORNECEDORES frn on (frn.Codfornecedor = prod.Codfornecedor)
;
CREATE VIEW VIEWVENDA (CODIGO, DATA, CODVENDEDOR, VENDEDOR, CODCLIENTE, CLIENTE, CPF_CNPJ, CEPCLIENTE, CIDADECLIENTE, FONECLIENTE, ENDERECOCLIENTE, TOTALDESCTO, TOTAL)
AS 
select
    V.CODIGO,
    V.DATA,
    V.IDVENDEDOR,
    VD.VENDEDOR,
    V.CODCLIENTE,
    CLI.NOME,
    CLI.CPF_CNPJ,
    CLI.CEP, 
    CID.DESCRICAO,
    CLI.TELEFONE,
    CLI.ENDERECO,
    V.TOTALDESCTO,
    V.TOTAL
  FROM VENDA V
  LEFT JOIN VENDEDOR VD ON (VD.IDVENDEDOR = V.IDVENDEDOR)
  LEFT JOIN CLIENTES CLI ON (CLI.CODCLIENTE = V.CODCLIENTE)
  LEFT JOIN CIDADES CID ON (CLI.CODCIDADE = CID.CODCIDADE)
;
/******************* EXCEPTIONS *******************/

CREATE EXCEPTION EXC_EXCLUSAO_PERFIL
'N�o � permitida a exclus�o deste perfil';
CREATE EXCEPTION EXC_EXCLUSAO_REGISTRO
'N�o � permitido excluir este registro pois ele � padr�o.';
CREATE EXCEPTION EXC_INCLUSAO_REGISTRO
'N�o � permitido incluir registros nesta tabela.';
/******************** TRIGGERS ********************/

SET TERM ^ ;
CREATE TRIGGER TRGLOG_AGENDA_ID FOR LOG_AGENDA ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN
  NEW.IDLOG_AGENDA = GEN_ID(GENIDLOG_AGENDA, 1);
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRGLOG_ALIQUOTAS_ID FOR LOG_ALIQUOTAS ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN
  NEW.IDLOG_ALIQUOTAS = GEN_ID(GENIDLOG_ALIQUOTAS, 1);
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRGLOG_DELAGENDA FOR AGENDA ACTIVE
AFTER DELETE POSITION 100
AS 
DECLARE VARIABLE IDLOGOPER INTEGER;
DECLARE VARIABLE USUARIO VARCHAR(10);
BEGIN
  /* Se houver log aberto para a conex�o corrente ent�o vincula a opera��o
     a esse log, do contr�rio a vari�vel ser� NULL e o log n�o vinculado. */
  SELECT MAX(IDLOGOPERACAO), USUARIO
    FROM LOGOPERACAO
   WHERE IDCONNECTION = CURRENT_CONNECTION AND ABERTO = 1
   GROUP BY USUARIO
    INTO :IDLOGOPER, :USUARIO;

  IF (:IDLOGOPER IS NOT NULL) THEN
  BEGIN
    INSERT INTO LOG_AGENDA (
      TIPOOPERACAO,
      USUARIO,
      DATAHORA,
      IDLOGOPERACAO,
      IDAGENDA,
      NOME,
      TELEFONE,
      FAX
      )
    VALUES (
      'D',
      :USUARIO,
      CURRENT_TIMESTAMP,
      :IDLOGOPER,
      OLD.IDAGENDA,
      OLD.NOME,
      OLD.TELEFONE,
      OLD.FAX
      );
  END
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRGLOG_DELALIQUOTAS FOR ALIQUOTAS ACTIVE
AFTER DELETE POSITION 100
AS 
DECLARE VARIABLE IDLOGOPER INTEGER;
DECLARE VARIABLE USUARIO VARCHAR(10);
BEGIN
  /* Se houver log aberto para a conex�o corrente ent�o vincula a opera��o
     a esse log, do contr�rio a vari�vel ser� NULL e o log n�o vinculado. */
  SELECT MAX(IDLOGOPERACAO), USUARIO
    FROM LOGOPERACAO
   WHERE IDCONNECTION = CURRENT_CONNECTION AND ABERTO = 1
   GROUP BY USUARIO
    INTO :IDLOGOPER, :USUARIO;

  IF (:IDLOGOPER IS NOT NULL) THEN
  BEGIN
    INSERT INTO LOG_ALIQUOTAS (
      TIPOOPERACAO,
      USUARIO,
      DATAHORA,
      IDLOGOPERACAO,
      CODALIQUOTA,
      DESCRICAO
      )
    VALUES (
      'D',
      :USUARIO,
      CURRENT_TIMESTAMP,
      :IDLOGOPER,
      OLD.CODALIQUOTA,
      OLD.DESCRICAO
      );
  END
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRGLOG_INSAGENDA FOR AGENDA ACTIVE
AFTER INSERT POSITION 100
AS 
DECLARE VARIABLE IDLOGOPER INTEGER;
DECLARE VARIABLE USUARIO VARCHAR(10);
BEGIN
  /* Se houver log aberto para a conex�o corrente ent�o vincula a opera��o
     a esse log, do contr�rio a vari�vel ser� NULL e o log n�o vinculado. */
  SELECT MAX(IDLOGOPERACAO), USUARIO
    FROM LOGOPERACAO
   WHERE IDCONNECTION = CURRENT_CONNECTION AND ABERTO = 1
   GROUP BY USUARIO
    INTO :IDLOGOPER, :USUARIO;

  IF (:IDLOGOPER IS NOT NULL) THEN
  BEGIN
    INSERT INTO LOG_AGENDA (
      TIPOOPERACAO,
      USUARIO,
      DATAHORA,
      IDLOGOPERACAO,
      IDAGENDA,
      NOME,
      TELEFONE,
      FAX
      )
    VALUES (
      'I',
      :USUARIO,
      CURRENT_TIMESTAMP,
      :IDLOGOPER,
      NEW.IDAGENDA,
      NEW.NOME,
      NEW.TELEFONE,
      NEW.FAX
      );
  END
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRGLOG_INSALIQUOTAS FOR ALIQUOTAS ACTIVE
AFTER INSERT POSITION 100
AS 
DECLARE VARIABLE IDLOGOPER INTEGER;
DECLARE VARIABLE USUARIO VARCHAR(10);
BEGIN
  /* Se houver log aberto para a conex�o corrente ent�o vincula a opera��o
     a esse log, do contr�rio a vari�vel ser� NULL e o log n�o vinculado. */
  SELECT MAX(IDLOGOPERACAO), USUARIO
    FROM LOGOPERACAO
   WHERE IDCONNECTION = CURRENT_CONNECTION AND ABERTO = 1
   GROUP BY USUARIO
    INTO :IDLOGOPER, :USUARIO;

  IF (:IDLOGOPER IS NOT NULL) THEN
  BEGIN
    INSERT INTO LOG_ALIQUOTAS (
      TIPOOPERACAO,
      USUARIO,
      DATAHORA,
      IDLOGOPERACAO,
      CODALIQUOTA,
      DESCRICAO
      )
    VALUES (
      'I',
      :USUARIO,
      CURRENT_TIMESTAMP,
      :IDLOGOPER,
      NEW.CODALIQUOTA,
      NEW.DESCRICAO
      );
  END
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRGLOG_UPDAGENDA FOR AGENDA ACTIVE
AFTER UPDATE POSITION 100
AS 
DECLARE VARIABLE IDLOGOPER INTEGER;
DECLARE VARIABLE USUARIO VARCHAR(10);
BEGIN
  /* Se houver log aberto para a conex�o corrente ent�o vincula a opera��o
     a esse log, do contr�rio a vari�vel ser� NULL e o log n�o vinculado. */
  SELECT MAX(IDLOGOPERACAO), USUARIO
    FROM LOGOPERACAO
   WHERE IDCONNECTION = CURRENT_CONNECTION AND ABERTO = 1
   GROUP BY USUARIO
    INTO :IDLOGOPER, :USUARIO;

  IF (:IDLOGOPER IS NOT NULL) THEN
  BEGIN
    INSERT INTO LOG_AGENDA (
      TIPOOPERACAO,
      USUARIO,
      DATAHORA,
      IDLOGOPERACAO,
      IDAGENDA,
      NOME,
      TELEFONE,
      FAX
      )
    VALUES (
      'U',
      :USUARIO,
      CURRENT_TIMESTAMP,
      :IDLOGOPER,
      NEW.IDAGENDA,
      NEW.NOME,
      NEW.TELEFONE,
      NEW.FAX
      );
  END
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRGLOG_UPDALIQUOTAS FOR ALIQUOTAS ACTIVE
AFTER UPDATE POSITION 100
AS 
DECLARE VARIABLE IDLOGOPER INTEGER;
DECLARE VARIABLE USUARIO VARCHAR(10);
BEGIN
  /* Se houver log aberto para a conex�o corrente ent�o vincula a opera��o
     a esse log, do contr�rio a vari�vel ser� NULL e o log n�o vinculado. */
  SELECT MAX(IDLOGOPERACAO), USUARIO
    FROM LOGOPERACAO
   WHERE IDCONNECTION = CURRENT_CONNECTION AND ABERTO = 1
   GROUP BY USUARIO
    INTO :IDLOGOPER, :USUARIO;

  IF (:IDLOGOPER IS NOT NULL) THEN
  BEGIN
    INSERT INTO LOG_ALIQUOTAS (
      TIPOOPERACAO,
      USUARIO,
      DATAHORA,
      IDLOGOPERACAO,
      CODALIQUOTA,
      DESCRICAO
      )
    VALUES (
      'U',
      :USUARIO,
      CURRENT_TIMESTAMP,
      :IDLOGOPER,
      NEW.CODALIQUOTA,
      NEW.DESCRICAO
      );
  END
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRIG_EXCLUSAO_ITEMPERFIL FOR ITEMPERFIL ACTIVE
BEFORE DELETE POSITION 0
AS
begin
  IF (OLD.IDPERFIL = 1) then
    EXCEPTION EXC_EXCLUSAO_PERFIL;
end^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRIG_EXCLUSAO_PERFIL FOR PERFIL ACTIVE
BEFORE DELETE POSITION 0
AS
begin
  IF (OLD.IDPERFIL = 1) then
    EXCEPTION EXC_EXCLUSAO_PERFIL;
end^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRIG_PERDA_ALTERACAO FOR PERDA ACTIVE
BEFORE UPDATE POSITION 0
AS
BEGIN
  UPDATE Produtos SET Estoque = Estoque + OLD.Qtde
    WHERE IdProduto = OLD.CodProduto;
  UPDATE Produtos SET Estoque = Estoque - NEW.Qtde
    WHERE IdProduto = NEW.CodProduto;
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRIG_PERDA_EXCLUSAO FOR PERDA ACTIVE
BEFORE DELETE POSITION 0
AS
BEGIN
  UPDATE Produtos SET Estoque = Estoque + OLD.Qtde
  WHERE IdProduto = OLD.CodProduto;
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRIG_PERDA_INCLUSAO FOR PERDA ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  UPDATE Produtos SET Estoque = Estoque - NEW.Qtde
  WHERE IdProduto = NEW.CodProduto;
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRIG_PROMOCAO_ALTERACAO FOR PROMOCAO ACTIVE
BEFORE UPDATE POSITION 0
AS
BEGIN
  UPDATE Produtos p SET p.PRECO_PROMOCAO = OLD.PRECO
  WHERE p.IDPRODUTO = OLD.PRODUTO;
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRIG_PROMOCAO_EXCLUSAO FOR PROMOCAO ACTIVE
BEFORE DELETE POSITION 0
AS
BEGIN
  update Produtos p set p.PRECO_PROMOCAO = p.VENDA
    where p.IDPRODUTO = OLD.PRODUTO;
  update PRODUTOS p set p.PROMOCAO = 'N'
    where p.IDPRODUTO = OLD.PRODUTO;
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRIG_PROMOCAO_INSERCAO FOR PROMOCAO ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  update Produtos p set p.PRECO_PROMOCAO = new.PRECO
    where p.IDPRODUTO = new.PRODUTO;
  update PRODUTOS p set p.PROMOCAO = 'S'
    where p.IDPRODUTO = new.PRODUTO;
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRIG_SISTEMA_EXCLUSAO FOR SISTEMA ACTIVE
BEFORE DELETE POSITION 0
AS
BEGIN
  IF (OLD.Idsistema = 1) then
    EXCEPTION Exc_Exclusao_Registro;
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TRIG_SISTEMA_INCLUSAO FOR SISTEMA ACTIVE
BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE n INTEGER;
BEGIN
  SELECT COUNT(1) FROM Sistema INTO :n;
  IF (n >= 1) THEN
    EXCEPTION Exc_Inclusao_Registro;
end^
SET TERM ; ^

SET TERM ^ ;
ALTER PROCEDURE STPABRELOGOPERACAO (
    ORIGEM Varchar(80),
    USUARIO Varchar(10) )
AS
BEGIN
  insert into LOGOPERACAO
    (IDLOGOPERACAO,
     IDCONNECTION,
     ORIGEM,
     USUARIO,
     DATAHORA,
     ABERTO)
   values
     (GEN_ID(GENIDLOGOPERACAO, 1),
      CURRENT_CONNECTION,
      :origem,
      :usuario,
      CURRENT_TIMESTAMP,
      1);
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPBAIXACOMPRA (
    CODIGO Integer )
AS
DECLARE VARIABLE VIDPRODUTO INTEGER;
DECLARE VARIABLE VQTDE INTEGER;
DECLARE VARIABLE VCUSTO NUMERIC(13,2);
DECLARE VARIABLE VLUCRO NUMERIC(13,2);
DECLARE VARIABLE VVENDA NUMERIC(13,2);
DECLARE VARIABLE VIDFORN INTEGER;
DECLARE VARIABLE VQTDERECEB INTEGER;
DECLARE VARIABLE VDATARECEB DATE;
BEGIN
  FOR SELECT
        inf.Produto,
        inf.Qtde,
        inf.Custo,
        inf.Lucro,
        inf.Venda,
        nf.Codfornecedor,
        inf.Qtde,
        cast(CURRENT_DATE AS DATE) AS DATA_RECEB
      FROM Itemnotafiscal inf
      LEFT JOIN Notas_Fiscais nf ON (nf.Numero = inf.Numero)
     WHERE (inf.Numero = :Codigo)
      INTO :VIDPRODUTO,
           :VQTDE, 
           :VCUSTO, 
           :VLUCRO, 
           :VVENDA,
           :VIDFORN,
           :VQTDERECEB,
           :VDATARECEB
  DO
  BEGIN
    UPDATE Produtos p SET
      p.Estoque = (p.Estoque + :VQTDE),
      p.Custo = :VCUSTO,
      p.Lucro = :VLUCRO,
      p.Venda = :VVENDA,
      p.Codfornecedor = :VIDFORN,
      p.Qtderecebida = :VQTDERECEB,
      p.Datarecebida = :VDATARECEB
    WHERE p.Idproduto = :VIDPRODUTO;
  END

  UPDATE Notas_Fiscais SET BAIXADO = 'S'
   WHERE NUMERO = :Codigo;

  SUSPEND;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPBAIXAVENDA (
    CODIGO Integer )
AS
DECLARE VARIABLE VIDPRODUTO INTEGER;
DECLARE VARIABLE VQTDE INTEGER;
BEGIN
  FOR SELECT
        iv.Codproduto,
        iv.Qtd
      FROM Itemvenda iv
     WHERE iv.Codigo = :Codigo
      INTO :VIDPRODUTO,
           :VQTDE
  DO
  BEGIN
    UPDATE Produtos p set
      p.Estoque = (p.Estoque - :VQTDE)
    WHERE p.Idproduto = :VIDPRODUTO;
  END

  UPDATE Venda SET BAIXADO = 'S'
   WHERE CODIGO = :Codigo;

  SUSPEND;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPCAIXASPADRAO (
    ID Integer )
AS
BEGIN
  UPDATE CAIXA cx SET cx.Codcaixas = :ID
    WHERE (cx.Codcaixas IS NULL);
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPCONFIGPADRAO (
    COMPUTADOR Varchar(80),
    DIREXP Varchar(150) )
AS
declare variable IDCONTACAIXA integer;
declare variable CAIXA integer;
BEGIN
  select contacheque from configuracao into :caixa;
  select max(codigo)+1 from caixas into :IDCONTACAIXA;

   /* se n�o tiver conta configurada de cheque ent�o cadastra */
  IF ((:CAIXA is null) or (:CAIXA = 0)) THEN
  BEGIN
    INSERT INTO CAIXAS(CODIGO, NOME, INATIVO)
    VALUES(:IDCONTACAIXA, 'CHEQUES', 'N');
  END

  /* configura��es padronizadas na primeira abertura do sistema */
  INSERT INTO CONFIGURACAO
  VALUES (gen_id(GENIDCONFIGURACAO,1), :COMPUTADOR, 'S', 'S', 'S', 'S', 'S', 'N', 'S', 'S', 'N', 'S',
          :DIREXP, '563412', 'S', 10, 'N', 1, 1, 1, '563412', 'S', 'S', 'N',
          'S', 'N', 'S', 'S', 'N', 'N', 'N', 'S', 'S', 'N', :IDCONTACAIXA, 'S');
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPDELCAIXA (
    CODIGO Integer )
AS
BEGIN
  DELETE FROM CAIXA WHERE CODCAIXA = :CODIGO;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPDELCP (
    CODIGO Integer )
AS
DECLARE VARIABLE VDOC VARCHAR(20);
DECLARE VARIABLE VPAGA CHAR(1);
BEGIN
  /* busca o documento e se a conta j� foi paga */
   SELECT
     cr.Documento,
     cr.Paga
   FROM Contaspagar cr
  WHERE cr.Codigo = :Codigo
   INTO :VDOC,
        :VPAGA;

  /* deleta a conta */
  DELETE FROM Contaspagar cr
   WHERE cr.Codigo = :Codigo;

  /* caso a conta j� tenha sido paga, elimina ela do caixa tamb�m */
  IF (:VPAGA = 'S') THEN
    DELETE FROM Caixa c
     WHERE c.Documento = :VDOC;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPDELCR (
    CODIGO Integer )
AS
DECLARE VARIABLE VDOC VARCHAR(20);
DECLARE VARIABLE VRECDA CHAR(1);
BEGIN
  /* busca o documento e se a conta foi recebida */
   SELECT
     cr.Documento,
     cr.Recda
   FROM Contasreceber cr
  WHERE cr.Codigo = :Codigo
   INTO :VDOC,
        :VRECDA;

  /* exclui o lan�amento */
  DELETE FROM Contasreceber cr
   WHERE cr.Codigo = :Codigo;

  /* se o conta j� foi recebida, exclui o lan�amento no caixa tamb�m */
  IF (:VRECDA = 'S') THEN
    DELETE FROM Caixa c
     WHERE c.Documento = :VDOC;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPDELDUPLICATA (
    CODIGO Integer )
AS
BEGIN
  DELETE FROM Duplicata dpc WHERE dpc.Idduplicata = :Codigo;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPDELETQPRODUTO (
    CODIGO Varchar(13) )
AS
BEGIN
  DELETE FROM ETIQUETAPROD e WHERE e.CODBARRA = :CODIGO;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPDELORCAMENTO (
    CODIGO Integer )
AS
BEGIN
  DELETE FROM ITEMORCAMENTO io WHERE io.CODIGO = :CODIGO;
  DELETE FROM ORCAMENTO o WHERE o.Codigo = :CODIGO;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPDELVENDA (
    CODIGO Integer )
AS
DECLARE VARIABLE VNUMCHEQUE VARCHAR(20);
BEGIN
  /* deleta regsitro de recebimento da venda */
  delete from RECTOVENDA rv
    where rv.IDVENDA = :CODIGO;

  /* deleta registros do crediario da venda */
  delete from CONTASRECEBER cr
    where cr.VENDA = :CODIGO;

  /* pega o numero do cheque que
     possivelmente possa ser utilizado */
  select
    c.NUMERO
  from CHEQUE c
  where c.VENDA = :CODIGO
  into :VNUMCHEQUE;

  /* deleta registro do caixa da venda */
  delete from CAIXA cx
    where ((cx.DOCUMENTO like '%V'||cast(:CODIGO as varchar(20))||'%')
       or  (cx.DOCUMENTO like :VNUMCHEQUE));

  /* delete cheques da venda */
  delete from CHEQUE  cq
   where cq.VENDA = :CODIGO;

  /* cancela a venda */
  update Venda v set
    v.Cancelado = 'S',
    V.Concluida = 'N'
   where v.Codigo = :Codigo;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPDESMARCAPROMOCAO
AS
BEGIN
  delete from PROMOCAO pro
  where pro.FIM < CURRENT_DATE;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPESTORNACOMPRA (
    CODIGO Integer )
AS
DECLARE VARIABLE VIDPRODUTO INTEGER;
DECLARE VARIABLE VQTDE INTEGER;
DECLARE VARIABLE VNUMCHEQUE VARCHAR(20);
BEGIN
  FOR SELECT
        inf.Produto,
        inf.QTDE
      FROM Itemnotafiscal inf
     WHERE inf.Numero = :CODIGO
      INTO :VIDPRODUTO,
           :VQTDE
  DO
  BEGIN
    UPDATE Produtos p set
      p.Estoque = (p.Estoque - :VQTDE)
     WHERE p.Idproduto = :VIDPRODUTO;
  END

  /* deleta regsitro de pagamento da compra */
  DELETE FROM Pagtocompra pc
   WHERE pc.Idcompra = :Codigo;

  /* deleta registros do contas a pagar da compra */
  DELETE FROM Contaspagar cp
   WHERE cp.Compra = :Codigo;

  SELECT
    c.Numero
    FROM Cheque c
   WHERE c.Compra = :Codigo
    INTO :VNUMCHEQUE;

  /* deleta registro do caixa da compra */
  DELETE FROM CAIXA cx
   WHERE ((cx.DOCUMENTO like '%C'||cast(:CODIGO as varchar(20))||'%')
      OR  (cx.DOCUMENTO like :VNUMCHEQUE));

  /* delete cheques da venda */
  DELETE FROM Cheque cq
   WHERE cq.Compra = :Codigo;

  /* coloca a venda como N�O conclu�da */
  UPDATE Notas_Fiscais nf set
    nf.Concluida = 'N',
    nf.Baixado   = 'N'
   WHERE nf.Numero = :Codigo;

  SUSPEND;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPESTORNAVENDA (
    CODIGO Integer )
AS
DECLARE VARIABLE VNUMCHEQUE VARCHAR(20);
DECLARE VARIABLE VCODPRODUTO INTEGER;
DECLARE VARIABLE VQTDE INTEGER;
begin
  for select
        iv.CODPRODUTO,
        iv.QTD
      from ITEMVENDA iv
      where iv.CODIGO = :CODIGO
      into :VCODPRODUTO,
           :VQTDE
  do
  begin
    update PRODUTOS p set
      p.ESTOQUE = (p.ESTOQUE + :VQTDE)
    where p.IDPRODUTO = :VCODPRODUTO;
  end

  /* deleta regsitro de recebimento da venda */
  delete from RECTOVENDA rv
    where rv.IDVENDA = :CODIGO;

  /* deleta registros do crediario da venda */
  delete from CONTASRECEBER cr
    where cr.VENDA = :CODIGO;

  select
    c.NUMERO
  from CHEQUE c
  where c.VENDA = :CODIGO
  into :VNUMCHEQUE;

  /* deleta registro do caixa da venda */
  delete from CAIXA cx
    where ((cx.DOCUMENTO like '%V'||cast(:CODIGO as varchar(20))||'%')
       or  (cx.DOCUMENTO like :VNUMCHEQUE));

  /* delete cheques da venda */
  delete from CHEQUE  cq
   where cq.VENDA = :CODIGO;

  /* coloca a venda como N�O conclu�da */
  update VENDA v set
    v.Concluida = 'N',
    v.Baixado   = 'N'
   where v.CODIGO = :CODIGO;

  SUSPEND;
end^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPFECHALOGOPERACAO
AS
BEGIN
  update LOGOPERACAO
     set ABERTO = 0
   where IDCONNECTION = CURRENT_CONNECTION
     and ABERTO = 1;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPGETCLIENTEANIVER (
    TIPO Integer,
    DIAINI Integer,
    DIAFIM Integer,
    MES Integer,
    ANO Integer,
    DATA1 Date,
    DATA2 Date )
RETURNS (
    NOME Varchar(50),
    DATANASC Date,
    ENDERECO Varchar(50),
    CIDADE Varchar(50),
    BAIRRO Varchar(50),
    CEP Varchar(20),
    FONE Varchar(20) )
AS
BEGIN
   if (:TIPO = 0) then -- por dia mes e ano
   begin
     for select
           wec.NOME,
           wec.DATA,
           wec.ENDERECO,
           wec.CIDADE,
           wec.BAIRRO,
           wec.CEP,
           cli.TELEFONE
         from VIEWENDERECOCLIENTES wec
         left join CLIENTES cli on (wec.Codigo = cli.Codcliente)
        where (extract(month from DATA) = :MES)
          and (extract(day from DATA) between :DIAINI and :DIAFIM)
          and ((:ANO = -1) or (:ANO IS NULL))
         into :NOME,
              :DATANASC,
              :ENDERECO,
              :CIDADE,
              :BAIRRO,
              :CEP,
              :FONE
     do
       suspend;
   end
   else if (:TIPO = 1) then --entre datas
   begin
     for select
           wec.NOME,
           wec.DATA,
           wec.ENDERECO,
           wec.CIDADE,
           wec.BAIRRO,
           wec.CEP,
           cli.TELEFONE
         from VIEWENDERECOCLIENTES wec
        inner join CLIENTES cli on (wec.Codigo = cli.Codcliente)
        where (DATA between :DATA1 and :DATA2)
         into :NOME,
              :DATANASC,
              :ENDERECO,
              :CIDADE,
              :BAIRRO,
              :CEP,
              :FONE
     do
       suspend;
   end
end^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPGETID (
    FIELDNAME Varchar(31),
    TABLENAME Varchar(31) )
RETURNS (
    ID Integer )
AS
begin
  execute statement 'select max('||:FIELDNAME||') from '||:TABLENAME into :ID;
  ID = ID + 1;
  suspend;
end^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPINSCAIXA (
    CONTA Integer,
    DATA Date,
    DESCRICAO Varchar(80),
    DOCUMENTO Varchar(20),
    TIPO Char(1),
    VALOR Numeric(13,4) )
AS
DECLARE VARIABLE ID INTEGER;
BEGIN
  EXECUTE PROCEDURE STPGETID('CODCAIXA', 'CAIXA') RETURNING_VALUES :ID;
  INSERT INTO CAIXA(CODCAIXA, CODCAIXAS, DATA, DESCRICAO, DOCUMENTO, TIPO, VALOR, EXCLUIR)
  VALUES(:ID, :CONTA, :DATA, :DESCRICAO, :DOCUMENTO, :TIPO, :VALOR, 'N');
  SUSPEND;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPINSCHEQUE (
    PIDBANCO Integer,
    PIDCLIENTE Integer,
    PIDFORN Integer,
    PBANDAMAGNETICA Varchar(35),
    PAGENCIA Varchar(20),
    PCONTA Varchar(20),
    PNUMERO Varchar(20),
    PDATAEMISSAO Date,
    PBOMPARA Date,
    PVALOR Numeric(13,4),
    PVENDA Integer,
    PCOMPRA Integer,
    PREPASSADO Char(1),
    PDATABAIXADO Date )
AS
DECLARE VARIABLE ID INTEGER;
BEGIN
  /* id do cheque */
  EXECUTE PROCEDURE STPGETID('IDCHEQUE', 'CHEQUE') RETURNING_VALUES :ID;

  /* lan�a o cheque */
  INSERT INTO CHEQUE(IDCHEQUE, IDBANCO, IDCLIENTE, IDFORN, BANDAMAGNETICA, AGENCIA, CONTA,
    NUMERO, DATAEMISSAO, BOMPARA, VALOR, VENDA, COMPRA, REPASSADO, DATABAIXADO)
  VALUES(:ID, :PIDBANCO, :PIDCLIENTE, :PIDFORN, :PBANDAMAGNETICA, :PAGENCIA, :PCONTA, 
    :PNUMERO, :PDATAEMISSAO, :PBOMPARA, :PVALOR, :PVENDA, :PCOMPRA, :PREPASSADO, :PDATABAIXADO);

  SUSPEND;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPPAGTOCOMPRA (
    IDCOMPRA Integer,
    DATAPAGTO Date,
    FORMAPAGTO Varchar(20),
    VALORPAGO Numeric(13,2) )
AS
DECLARE VARIABLE TOTALCOMPRA FLOAT;
DECLARE VARIABLE RESTO FLOAT;
DECLARE VARIABLE IDPAGTOCOMPRA INTEGER;
DECLARE VARIABLE RESTOATUAL FLOAT;
BEGIN

  SELECT nf.TOTAL FROM NOTAS_FISCAIS nf WHERE NUMERO = :IDCOMPRA INTO :TOTALCOMPRA;
  SELECT MAX(IDPAGTOCOMPRA) FROM PAGTOCOMPRA INTO :IDPAGTOCOMPRA;
  SELECT MIN(VALORRESTO) FROM PAGTOCOMPRA WHERE IDCOMPRA = :IDCOMPRA INTO :RESTOATUAL;

  IF ((:TOTALCOMPRA IS NULL) OR (:TOTALCOMPRA < 0)) THEN
    TOTALCOMPRA = 0;

  IF ((:RESTOATUAL IS NULL) OR (:RESTOATUAL < 0)) THEN
    RESTOATUAL = 0;

  IF ((:IDPAGTOCOMPRA IS NULL) OR (:IDPAGTOCOMPRA < 0)) THEN
    IDPAGTOCOMPRA = 0;
  IDPAGTOCOMPRA = IDPAGTOCOMPRA + 1;

  /* se o restoatual for zero, entende que ainda n�o foi feito nenhum pagamento */
  IF (:RESTOATUAL > 0) THEN
    RESTO = (:RESTOATUAL - :VALORPAGO);
  ELSE
    RESTO = :TOTALCOMPRA - (:VALORPAGO + :RESTOATUAL);

  IF ((:RESTO < 0) or (:RESTO IS NULL)) THEN
    RESTO = 0;

  insert into PAGTOCOMPRA
    (IDPAGTOCOMPRA, IDCOMPRA, DATAPAGTO, FORMAPAGTO, VALORPAGO, VALORRESTO)
  values(:IDPAGTOCOMPRA, :IDCOMPRA, :DATAPAGTO, :FORMAPAGTO, :VALORPAGO, :RESTO);

  /* s� conclui a compra caso n�o tenha mais resto,ou o valor a pagar for igual
     ao total da compra */
  IF ((:VALORPAGO = :TOTALCOMPRA) OR (:RESTO = 0)) THEN
    UPDATE NOTAS_FISCAIS SET CONCLUIDA = 'S'
    WHERE NUMERO = :IDCOMPRA;

  SUSPEND;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPPRODUTOSVENCIDOS (
    DATAVENC Date,
    IDUN Integer,
    IDGRUPO Integer,
    IDFORNECEDOR Integer )
RETURNS (
    CODBARRA Varchar(13),
    PRODUTO Varchar(50),
    DATAVENCIMENTO Date,
    UNIDADE Varchar(20),
    GRUPO Varchar(50),
    FORNECEDOR Varchar(50),
    PRECOCUSTO Numeric(13,2) )
AS
BEGIN
    FOR SELECT
      p.CODBARRA,
      p.DESCRICAO,
      p.Datavalidade,
      u.DESCRICAO,
      g.DESCRICAO,
      f.FANTAZIA,
      p.CUSTO
    FROM PRODUTOS p
    LEFT JOIN UNIDADES u ON (u.Codunidade = p.Codunidade)
    LEFT JOIN GRUPOS g ON (g.CODGRUPO = p.CODGRUPO)
    LEFT JOIN FORNECEDORES f ON (f.CODFORNECEDOR = p.CODFORNECEDOR)
    WHERE ((:IDUN = -1)or(p.Codunidade = :IDUN))
    AND ((:IDGRUPO = -1)or(p.Codgrupo = :IDGRUPO))
    AND ((:IDFORNECEDOR = -1)or(p.Codfornecedor = :IDFORNECEDOR))
    AND ((p.Datavalidade >= :DATAVENC))
    INTO :CODBARRA,
         :PRODUTO,
         :DATAVENCIMENTO,
         :UNIDADE,
         :GRUPO,
         :FORNECEDOR,
         :PRECOCUSTO
    DO
    BEGIN
      SUSPEND;
    END
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPRECTOVENDA (
    IDVENDA Integer,
    DATARECTO Date,
    FORMARECTO Varchar(20),
    VALORRECDO Numeric(13,2) )
AS
DECLARE VARIABLE TOTALVENDA FLOAT;
DECLARE VARIABLE RESTO FLOAT;
DECLARE VARIABLE IDRECTOVENDA INTEGER;
DECLARE VARIABLE RESTOATUAL FLOAT;
BEGIN

  SELECT v.TOTAL FROM VENDA v WHERE CODIGO = :IDVENDA INTO :TOTALVENDA;
  SELECT MAX(IDRECTOVENDA) FROM RECTOVENDA INTO :IDRECTOVENDA;
  SELECT MIN(VALORRESTO) FROM RECTOVENDA WHERE IDVENDA = :IDVENDA INTO :RESTOATUAL;

  if ((:TOTALVENDA is null) or (:TOTALVENDA < 0)) then
    TOTALVENDA = 0;

  if ((:IDRECTOVENDA is null) or (:IDRECTOVENDA < 0)) then
    IDRECTOVENDA = 0;
  IDRECTOVENDA = IDRECTOVENDA + 1;

  if ((:RESTOATUAL is null) or (:RESTOATUAL < 0)) then
    RESTOATUAL = 0;

  /* se o restoatual for zero, entende que ainda n�o foi feito nenhum recebimento */
  IF (:RESTOATUAL > 0) THEN
    RESTO = (:RESTOATUAL - :VALORRECDO);
  ELSE
    RESTO = :TOTALVENDA - (:VALORRECDO + :RESTOATUAL);

  IF ((:RESTO <= 0) or (:RESTO IS NULL)) THEN
    RESTO = 0;

  insert into RECTOVENDA
    (IDRECTOVENDA, IDVENDA, DATARECTO, FORMARECTO, VALORRECDO, VALORRESTO)
  values(:IDRECTOVENDA, :IDVENDA, :DATARECTO, :FORMARECTO, :VALORRECDO, :RESTO);

  /* s� conclui a venda caso n�o tenha mais resto ou o valor a receber for igual
     ao total da venda */
  IF ((:VALORRECDO = :TOTALVENDA) OR (:RESTO = 0)) THEN
    UPDATE VENDA SET CONCLUIDA = 'S'
    WHERE CODIGO = :IDVENDA;

  SUSPEND;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPRELCAIXAMESANO (
    MES Integer,
    ANO Integer,
    PORDEM Char(1) )
RETURNS (
    CODIGO Integer,
    DATA Date,
    DESCRICAO Varchar(80),
    DOCUMENTO Varchar(20),
    TIPO Char(1),
    VALOR Numeric(13,2),
    TOTALCREDITOS Numeric(13,2),
    TOTALDEBITOS Numeric(13,2),
    TOTALSALDO Numeric(13,2),
    TOTAL Numeric(13,2) )
AS
BEGIN
  /* Total creditos */
  SELECT SUM(VALOR)FROM VIEWRELCAIXA
         WHERE TIPO = 'C'
         AND EXTRACT(MONTH FROM DATA) = :MES
         AND EXTRACT(YEAR FROM DATA) = :ANO
         INTO :TOTALCREDITOS;

         if (TOTALCREDITOS IS NULL) then
           TOTALCREDITOS = 0;

  /* Total debitos */
  SELECT SUM(VALOR)FROM VIEWRELCAIXA
         WHERE TIPO = 'D'
         AND EXTRACT(MONTH FROM DATA) = :MES
         AND EXTRACT(YEAR FROM DATA) = :ANO
         INTO :TOTALDEBITOS;

         if (TOTALDEBITOS IS NULL) then
           TOTALDEBITOS = 0;

  /* Saldo */
  TOTALSALDO = TOTALCREDITOS - TOTALDEBITOS;

    FOR SELECT
       CODIGO,
       DATA,
       DESCRICAO,
       DOCUMENTO,
       TIPO,
       VALOR
     FROM VIEWRELCAIXA
     WHERE EXTRACT(MONTH FROM DATA) = :MES
     AND EXTRACT(YEAR FROM DATA) = :ANO
     ORDER BY
    
     case when :pordem = 'L' then
       CODIGO end,
     case when :pordem = 'D' then
       DATA end
    
     INTO
       :CODIGO,
       :DATA,
       :DESCRICAO,
       :DOCUMENTO,
       :TIPO,
       :VALOR
    DO
     SUSPEND;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPRELCAIXATIPOCONTA (
    PDATAINI Date,
    PDATAFIM Date,
    PTIPOCONTA Char(1),
    PORDEM Char(1) )
RETURNS (
    CODIGO Integer,
    TOTAL Numeric(13,2),
    DATA Date,
    DESCRICAO Varchar(80),
    DOCUMENTO Varchar(20),
    TIPO Char(1),
    VALOR Numeric(13,2) )
AS
BEGIN

  /* Total pelas datas e tipo de conta */
  SELECT
     SUM(VALOR)
    FROM VIEWRELCAIXA
   WHERE ((TIPO = :PTIPOCONTA) OR (:ptipoconta = 'T'))
     AND DATA BETWEEN :PDATAINI AND :PDATAFIM
    INTO :TOTAL;

  if (TOTAL IS NULL) then
    TOTAL = 0;

   FOR SELECT
      CODIGO,
      DATA,
      DESCRICAO,
      DOCUMENTO,
      TIPO,
      VALOR
    FROM VIEWRELCAIXA
    WHERE ((TIPO = :PTIPOCONTA) OR (:ptipoconta = 'T'))
    AND DATA BETWEEN :PDATAINI AND :PDATAFIM

    ORDER BY
      CASE WHEN :pordem = 'L' THEN CODIGO END,
      case WHEN :pordem = 'D' THEN DATA END

    INTO
      :CODIGO, 
      :DATA,
      :DESCRICAO, 
      :DOCUMENTO, 
      :TIPO, 
      :VALOR
   DO
     SUSPEND;
end^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPRESTOCOMPRA (
    PIDCOMPRA Integer )
RETURNS (
    RESTO Numeric(13,2) )
AS
DECLARE VARIABLE PAGO FLOAT;
DECLARE VARIABLE TOTAL_COMPRA FLOAT;
DECLARE VARIABLE COUNT_PAGTO SMALLINT;
begin
  TOTAL_COMPRA = 0;
  COUNT_PAGTO  = 0;
  RESTO        = 0;
  PAGO         = 0;

  select nf.TOTAL from NOTAS_FISCAIS nf where
  nf.NUMERO = :PIDCOMPRA into :TOTAL_COMPRA;

  select count(1) from PAGTOCOMPRA pc where
  pc.IDCOMPRA = :PIDCOMPRA into :COUNT_PAGTO;

  select
    sum(VALORPAGO)
  from PAGTOCOMPRA
  where IDCOMPRA = :PIDCOMPRA
  into :PAGO;

  if ((:COUNT_PAGTO is null)or(:COUNT_PAGTO <= 0)) then
    RESTO = TOTAL_COMPRA;
  else
    RESTO = (TOTAL_COMPRA - PAGO);

  if (RESTO < 0) then
    RESTO = 0;

  suspend;
end^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPRESTOVENDA (
    PIDVENDA Integer )
RETURNS (
    RESTO Numeric(13,2) )
AS
DECLARE VARIABLE RECDO FLOAT;
DECLARE VARIABLE COUNT_RECTO SMALLINT;
DECLARE VARIABLE TOTAL_VENDA FLOAT;
begin
  TOTAL_VENDA = 0;
  COUNT_RECTO = 0;
  RESTO       = 0;
  RECDO       = 0;

  select ve.TOTAL from VENDA ve where
  ve.CODIGO = :PIDVENDA into :TOTAL_VENDA;

  select count(1) from RECTOVENDA rv where
  rv.IDVENDA = :PIDVENDA into :COUNT_RECTO;

  select
    sum(VALORRECDO)
  from RECTOVENDA
  where IDVENDA = :PIDVENDA
  into :RECDO;

  if ((:COUNT_RECTO is null)or(:COUNT_RECTO <= 0)) then
    RESTO = TOTAL_VENDA;
  else
    RESTO = (TOTAL_VENDA - RECDO);

  if (RESTO < 0) then
    RESTO = 0;

  suspend;
end^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPSITUACAOCLIENTE (
    CODIGO Integer )
RETURNS (
    CLIENTE Varchar(80),
    LIMITECLIENTE Numeric(13,2),
    DATACADASTRO Date,
    TOTALCONTAS Numeric(13,2),
    TOTALCONTASVENCIDAS Numeric(13,2),
    PRIMEIROVENCIMENTO Date,
    DIASATRASO Integer )
AS
BEGIN

  /*Seleciona os valores da tabela clientes*/
  SELECT Nome, Limite, Cadastro FROM Clientes
   WHERE CodCliente = :Codigo
    INTO :CLIENTE, :LIMITECLIENTE, :DATACADASTRO;

  IF (LimiteCLIENTE IS NULL) THEN
    LimiteCLIENTE = 0;

  SELECT SUM(Total) FROM CONTASRECEBER
   WHERE (RECDA = 'N')
     AND (Cliente = :CODIGO)
    INTO :TOTALCONTAS;

  IF (TOTALCONTAS IS NULL) THEN
    TOTALCONTAS = 0;

  SELECT SUM(Total) FROM CONTASRECEBER
   WHERE (RECDA = 'N')
     AND (Cliente = :CODIGO)
     AND (Vencimento < CURRENT_TIMESTAMP)
    INTO :TOTALCONTASVENCIDAS;

  IF (TOTALCONTASVENCIDAS IS NULL) THEN
    TOTALCONTASVENCIDAS = 0;

  SELECT MIN(Vencimento) FROM CONTASRECEBER /* Primeiro vencto */
   WHERE (RECDA = 'N')
     AND (Cliente = :CODIGO)
    INTO :PRIMEIROVENCIMENTO;

  DIASATRASO = (CURRENT_DATE - :PRIMEIROVENCIMENTO);

  if (DIASATRASO IS NULL) then
    DIASATRASO = 0;

  SUSPEND;
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE STPVENDACOMISSAO (
    VENDEDOR Integer,
    DATAINI Date,
    DATAFIM Date )
RETURNS (
    CODPRODUTO Integer,
    DESCRICAO Varchar(150),
    QTD Integer,
    TOTAL Numeric(13,2),
    COMISSAO Numeric(13,2) )
AS
BEGIN
  FOR
    SELECT Produtos.IDPRODUTO, Produtos.DESCRICAO, SUM(ItemVenda.QTD),
      SUM(ItemVenda.TOTAL), SUM(ItemVenda.VALORCOMISSAO)
    FROM Venda, ItemVenda, Produtos
    WHERE
      Venda.IDVENDEDOR = :Vendedor AND
      Venda.DATA BETWEEN :DataIni AND :DataFim AND
      Venda.Concluida = 'S' AND
      ItemVenda.CODIGO = Venda.CODIGO AND
      Produtos.IDPRODUTO = ItemVenda.CODPRODUTO
    GROUP BY Produtos.IDPRODUTO, Produtos.Descricao
    ORDER BY Produtos.Descricao
    INTO :CodProduto, :Descricao, :Qtd, :Total, :Comissao
  DO
    SUSPEND;
END^
SET TERM ; ^


ALTER TABLE CAIXA ADD CONSTRAINT FK_CAIXA_CAIXAS
  FOREIGN KEY (CODCAIXAS) REFERENCES CAIXAS (CODIGO) ON UPDATE SET NULL ON DELETE SET NULL;
CREATE INDEX IDX_CAIXA_DATA ON CAIXA (DATA);
ALTER TABLE CHEQUE ADD CONSTRAINT FK_CHEQUE_BANCO
  FOREIGN KEY (IDBANCO) REFERENCES BANCO (IDBANCO) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CHEQUE ADD CONSTRAINT FK_CHEQUE_CLIENTE
  FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES (CODCLIENTE) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CHEQUE ADD CONSTRAINT FK_CHEQUE_COMPRA
  FOREIGN KEY (COMPRA) REFERENCES NOTAS_FISCAIS (NUMERO) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CHEQUE ADD CONSTRAINT FK_CHEQUE_FORN
  FOREIGN KEY (IDFORN) REFERENCES FORNECEDORES (CODFORNECEDOR) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CHEQUE ADD CONSTRAINT FK_CHEQUE_VENDA
  FOREIGN KEY (VENDA) REFERENCES VENDA (CODIGO) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_CIDADE
  FOREIGN KEY (CODCIDADE) REFERENCES CIDADES (CODCIDADE);
ALTER TABLE CONFIGURACAO ADD CONSTRAINT FK_CONFIGURACAO_ALIQUOTA
  FOREIGN KEY (ALIQUOTAPADRAO) REFERENCES ALIQUOTAS (CODALIQUOTA) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CONFIGURACAO ADD CONSTRAINT FK_CONFIGURACAO_CAIXA
  FOREIGN KEY (CAIXAPADRAO) REFERENCES CAIXAS (CODIGO) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CONFIGURACAO ADD CONSTRAINT FK_CONFIGURACAO_CONTACAIXA
  FOREIGN KEY (CONTACHEQUE) REFERENCES CAIXAS (CODIGO) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CONTASPAGAR ADD ATRASO COMPUTED BY (
    CASE
       WHEN Paga = 'N' AND VENCIMENTO < CURRENT_DATE THEN
         CURRENT_DATE - VENCIMENTO /* A receber em atraso */
       WHEN Paga = 'S' AND VENCIMENTO < DataPagto THEN
         DataPagto - VENCIMENTO /* Recebida em atraso */
       ELSE
         0
    END);
ALTER TABLE CONTASPAGAR ADD VALORJURO COMPUTED BY (CAST(Valor * Juro * Atraso / 100 / 30 AS FLOAT));
ALTER TABLE CONTASPAGAR ADD TOTAL COMPUTED BY (CAST(Valor + ValorJuro AS FLOAT));
ALTER TABLE CONTASPAGAR ADD TOTALPAGO COMPUTED BY (CAST(CapitalPago + JuroPago AS FLOAT));
ALTER TABLE CONTASPAGAR ADD CONSTRAINT FK_CONTASPAGAR_CONTA
  FOREIGN KEY (IDCONTA) REFERENCES CAIXAS (CODIGO);
ALTER TABLE CONTASPAGAR ADD CONSTRAINT FK_CONTASPAGAR_FORN
  FOREIGN KEY (FORNECEDOR) REFERENCES FORNECEDORES (CODFORNECEDOR);
ALTER TABLE CONTASRECEBER ADD ATRASO COMPUTED BY (
    CASE
       WHEN Recda = 'N' AND VENCIMENTO < CURRENT_DATE THEN
         CURRENT_DATE - VENCIMENTO
       WHEN Recda = 'S' AND VENCIMENTO < DataRecto THEN
         DataRecto - VENCIMENTO
       ELSE
         0
    END);
ALTER TABLE CONTASRECEBER ADD VALORJURO COMPUTED BY (CAST(Valor * Juro * Atraso / 100 / 30 AS FLOAT));
ALTER TABLE CONTASRECEBER ADD TOTAL COMPUTED BY (CAST(Valor + ValorJuro AS FLOAT));
ALTER TABLE CONTASRECEBER ADD TOTALRECDO COMPUTED BY (CAST(CapitalRecdo + JuroRecdo AS FLOAT));
ALTER TABLE CONTASRECEBER ADD CONSTRAINT FK_CONTASRECEBER_CLIENTE
  FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (CODCLIENTE);
ALTER TABLE CONTASRECEBER ADD CONSTRAINT FK_CONTASRECEBER_CONTA
  FOREIGN KEY (IDCONTA) REFERENCES CAIXAS (CODIGO);
ALTER TABLE DUPLICATA ADD CONSTRAINT FK_DUPLICATA_CIDADE
  FOREIGN KEY (IDCIDADE) REFERENCES CIDADES (CODCIDADE);
ALTER TABLE EMPRESA ADD CONSTRAINT FK_EMPRESA_CIDADE
  FOREIGN KEY (IDCIDADE) REFERENCES CIDADES (CODCIDADE);
ALTER TABLE ENVELOPE ADD CONSTRAINT FK_ENVELOPE_CIDADE
  FOREIGN KEY (IDCIDADE) REFERENCES CIDADES (CODCIDADE);
ALTER TABLE FORNECEDORES ADD CONSTRAINT FK_FORNECEDORES_CIDADE
  FOREIGN KEY (CIDADE) REFERENCES CIDADES (CODCIDADE);
ALTER TABLE ITEMNOTAFISCAL ADD CONSTRAINT FK_ITEMNOTAFISCAL_ALIQUOTA
  FOREIGN KEY (ALIQUOTA) REFERENCES ALIQUOTAS (CODALIQUOTA);
ALTER TABLE ITEMNOTAFISCAL ADD CONSTRAINT FK_ITEMNOTAFISCAL_NOTAFISCAL
  FOREIGN KEY (NUMERO) REFERENCES NOTAS_FISCAIS (NUMERO);
ALTER TABLE ITEMNOTAFISCAL ADD CONSTRAINT FK_ITEMNOTAFISCAL_PRODUTO
  FOREIGN KEY (PRODUTO) REFERENCES PRODUTOS (IDPRODUTO);
ALTER TABLE ITEMORCAMENTO ADD CONSTRAINT FK_ITEMORCAMENTO_ORCAM
  FOREIGN KEY (CODIGO) REFERENCES ORCAMENTO (CODIGO);
ALTER TABLE ITEMORCAMENTO ADD CONSTRAINT FK_ITEMORCAMENTO_PRODUTO
  FOREIGN KEY (CODPRODUTO) REFERENCES PRODUTOS (IDPRODUTO);
ALTER TABLE ITEMPERFIL ADD CONSTRAINT FK_ITEMPERFIL_PERFIL
  FOREIGN KEY (IDPERFIL) REFERENCES PERFIL (IDPERFIL) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE ITEMVENDA ADD CONSTRAINT FK_ITEMVENDA_PRODUTO
  FOREIGN KEY (CODPRODUTO) REFERENCES PRODUTOS (IDPRODUTO);
ALTER TABLE ITEMVENDA ADD CONSTRAINT FK_ITEMVENDA_VENDA
  FOREIGN KEY (CODIGO) REFERENCES VENDA (CODIGO);
CREATE INDEX IX_LOG_AGENDA_DU ON LOG_AGENDA (DATAHORA,USUARIO);
CREATE INDEX IX_LOG_AGENDA_LO ON LOG_AGENDA (IDLOGOPERACAO);
CREATE INDEX IX_LOG_AGENDA_PK ON LOG_AGENDA (IDAGENDA);
CREATE INDEX IX_LOG_AGENDA_U ON LOG_AGENDA (USUARIO);
CREATE INDEX IX_LOG_ALIQUOTAS_DU ON LOG_ALIQUOTAS (DATAHORA,USUARIO);
CREATE INDEX IX_LOG_ALIQUOTAS_LO ON LOG_ALIQUOTAS (IDLOGOPERACAO);
CREATE INDEX IX_LOG_ALIQUOTAS_PK ON LOG_ALIQUOTAS (CODALIQUOTA);
CREATE INDEX IX_LOG_ALIQUOTAS_U ON LOG_ALIQUOTAS (USUARIO);
ALTER TABLE NOTAS_FISCAIS ADD CONSTRAINT FK_NOTAS_FISCAIS_FORN
  FOREIGN KEY (CODFORNECEDOR) REFERENCES FORNECEDORES (CODFORNECEDOR);
ALTER TABLE ORCAMENTO ADD CONSTRAINT FK_ORCAMENTO_CLIENTE
  FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTES (CODCLIENTE);
ALTER TABLE ORCAMENTO ADD CONSTRAINT FK_ORCAMENTO_VENDEDOR
  FOREIGN KEY (IDVENDEDOR) REFERENCES VENDEDOR (IDVENDEDOR);
ALTER TABLE PAGTOCOMPRA ADD CONSTRAINT FK_PAGTOCOMPRA_COMPRA
  FOREIGN KEY (IDCOMPRA) REFERENCES NOTAS_FISCAIS (NUMERO) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE PERDA ADD CONSTRAINT FK_PERDA_PRODUTO
  FOREIGN KEY (CODPRODUTO) REFERENCES PRODUTOS (IDPRODUTO);
ALTER TABLE PRODUTOS ADD VALOR_ESTOQUE COMPUTED BY (
    CASE
      WHEN (ESTOQUE > 0) AND (CUSTO > 0) THEN
        CAST(ESTOQUE * CUSTO AS FLOAT)
      ELSE
        CAST(0 AS FLOAT)
    END);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_ALIQUOTA
  FOREIGN KEY (IDALIQUOTA) REFERENCES ALIQUOTAS (CODALIQUOTA);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_FORN
  FOREIGN KEY (CODFORNECEDOR) REFERENCES FORNECEDORES (CODFORNECEDOR);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_GRUPO
  FOREIGN KEY (CODGRUPO) REFERENCES GRUPOS (CODGRUPO);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_UNIDADE
  FOREIGN KEY (CODUNIDADE) REFERENCES UNIDADES (CODUNIDADE);
ALTER TABLE PROMOCAO ADD CONSTRAINT FK_PROMOCAO_PRODUTO
  FOREIGN KEY (PRODUTO) REFERENCES PRODUTOS (IDPRODUTO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE RECTOVENDA ADD CONSTRAINT FK_RECTOVENDA_VENDA
  FOREIGN KEY (IDVENDA) REFERENCES VENDA (CODIGO) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_PERFIL
  FOREIGN KEY (IDPERFIL) REFERENCES PERFIL (IDPERFIL) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_CLIENTE
  FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTES (CODCLIENTE);
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_VENDEDOR
  FOREIGN KEY (IDVENDEDOR) REFERENCES VENDEDOR (IDVENDEDOR);
GRANT EXECUTE
 ON PROCEDURE STPABRELOGOPERACAO TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPBAIXACOMPRA TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPBAIXAVENDA TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPCAIXASPADRAO TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPCONFIGPADRAO TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPDELCAIXA TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPDELCP TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPDELCR TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPDELDUPLICATA TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPDELETQPRODUTO TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPDELORCAMENTO TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPDELVENDA TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPDESMARCAPROMOCAO TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPESTORNACOMPRA TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPESTORNAVENDA TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPFECHALOGOPERACAO TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPGETCLIENTEANIVER TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPGETID TO PROCEDURE STPCONFIGPADRAO;

GRANT EXECUTE
 ON PROCEDURE STPGETID TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPINSCAIXA TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPINSCHEQUE TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPPAGTOCOMPRA TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPPRODUTOSVENCIDOS TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPRECTOVENDA TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPRELCAIXAMESANO TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPRELCAIXATIPOCONTA TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPRESTOCOMPRA TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPRESTOVENDA TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPSITUACAOCLIENTE TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE STPVENDACOMISSAO TO  SYSDBA;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON AGENDA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ALIQUOTAS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON BANCO TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CAIXA TO  SYSDBA WITH GRANT OPTION;

GRANT INSERT
 ON CAIXAS TO PROCEDURE STPCONFIGPADRAO;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CAIXAS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CFOP TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CHEQUE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CIDADES TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CLIENTES TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CONFIGDUPLICATA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CONFIGNOTA TO  SYSDBA WITH GRANT OPTION;

GRANT INSERT, SELECT
 ON CONFIGURACAO TO PROCEDURE STPCONFIGPADRAO;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CONFIGURACAO TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CONFIGURACAOGLOBAL TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CONTASPAGAR TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CONTASRECEBER TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON DUPLICATA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON EMPRESA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVELOPE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ETIQUETA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ETIQUETAPROD TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON FORNECEDORES TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON GRUPOS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ITEMNOTAFISCAL TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ITEMORCAMENTO TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ITEMPERFIL TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ITEMVENDA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LOGERRO TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LOGOPERACAO TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LOG_AGENDA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LOG_ALIQUOTAS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON MENSAGEM TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON NOTAS_FISCAIS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ORCAMENTO TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PAGTOCOMPRA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PERDA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PERFIL TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PRODUTOS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PROMOCAO TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RECIBO TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RECTOVENDA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON SISTEMA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON UNIDADES TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON USUARIOS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VENDA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VENDEDOR TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWAGENDA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWCAIXA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWCAIXAS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWCAIXASATIVOS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWCHEQUE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWEMPRESA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWENDERECOCLIENTES TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWETIQUETACLIENTE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWFICHACLIENTE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWFK TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWFORNECEDORES TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWITEMVENDA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWPERDAS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWPESQUISAFONE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWPESQUISAPRECO TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWPK TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWPRODUTOSMINIMOS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWRELCAIXA TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWRELCAIXACAIXAS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWRELCAIXATODOS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWRELCLIENTES TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWRELCP TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWRELCPATRASADOS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWRELCR TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWRELCRATRASADOS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWRELFORN TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWRELNPCR TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWRELPRODUTOS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEWVENDA TO  SYSDBA WITH GRANT OPTION;

