delete from agenda;

delete from banco;
delete from caixa;
delete from configuracao;

delete from caixas;

insert into caixas values(1,'GERAL','N');
insert into caixas values(2,'CHEQUES','N');
commit work;

delete from cheque;

delete from itemvenda;
delete from venda;

delete from itemorcamento;
delete from orcamento;

delete from ITEMNOTAFISCAL;
delete from notas_fiscais;

delete from clientes;

delete from contaspagar;
delete from contasreceber;
delete from duplicata;
delete from empresa;
delete from envelope;
delete from etiquetaprod;
delete from fornecedores;
delete from cidades where codcidade < 5571;
delete from grupos;

delete from ITEMPERFIL;
delete from perfil;

insert into perfil values(1,'ADM');

commit work;

INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (1, 1, 'actCidade', 'Cidades', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (2, 1, 'actUnidade', 'Unidades de medida', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (3, 1, 'actGrupo', 'Grupos de produtos', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (4, 1, 'actAliquotaIcms', 'Alíquotas de icms', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (58, 1, 'actContaCaixa', 'Contas caixa', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (5, 1, 'actCfop', 'Operações CFOP', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (6, 1, 'actConfiguracaoGlobal', 'Configurações globais', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (7, 1, 'actConfiguracaoLocal', 'Configurações locais', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (8, 1, 'actImpressora', 'Impressora', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (10, 1, 'actDadosEmpresa', 'Dados da empresa', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (11, 1, 'actUsuario', 'Usuários do sistema', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (12, 1, 'actPerfis', 'Perfis', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (13, 1, 'actTrocaSenha', 'Trocar minha senha', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (14, 1, 'actAgenda', 'Agenda de telefones', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (15, 1, 'actCalendario', 'Calendário', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (16, 1, 'actCalculadora', 'Calculadora', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (17, 1, 'actEditorTexto', 'Editor de texto', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (18, 1, 'actDuplicata', 'Duplicatas', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (19, 1, 'actNotaPromissoria', 'Nota promissória', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (20, 1, 'actRecibo', 'Recibos', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (21, 1, 'actRelatorioAgenda', 'Relatório de agenda', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (22, 1, 'actCliente', 'Clientes', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (23, 1, 'actProduto', 'Produtos', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (24, 1, 'actFornecedor', 'Fornecedores', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (25, 1, 'actContasPagar', 'Contas a pagar', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (26, 1, 'actContasReceber', 'Contas a receber', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (27, 1, 'actOrcamento', 'Orçamentos', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (28, 1, 'actVenda', 'Vendas', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (29, 1, 'actCompra', 'Compras', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (30, 1, 'actPerda', 'Perdas', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (31, 1, 'actCaixa', 'Livro caixa', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (32, 1, 'actDesmarcaProduto', 'Desmarcar produtos novos e alterados', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (33, 1, 'actListaPreco', 'Lista de preços', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (34, 1, 'actExcluirProduto', 'Exclusão de vários produtos', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (35, 1, 'actEtiquetaProduto', 'Etiquetas de produtos', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (36, 1, 'actFechar', 'Sair do sistema', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (37, 1, 'actOutroUsuario', 'Outro usuário', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (38, 1, 'actSobreSistema', 'Sobre', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (39, 1, 'actDicaDia', 'Dica do dia', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (40, 1, 'actEnvelope', 'Envelope personalizado', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (41, 1, 'actBackup', 'Cópia de segurança', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (42, 1, 'actRestore', 'Restauração', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (43, 1, 'actEtiqueta', 'Etiquetas', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (44, 1, 'actPesqFone', 'Pesquisa telefones', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (45, 1, 'actBanco', 'Bancos', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (46, 1, 'actCheque', 'Cheques', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (47, 1, 'actRenovaChave', 'Renovar chave de liberação', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (48, 1, 'actAtualizacao', 'Verificar atualização', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (49, 1, 'actPostIt', 'Post it', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (50, 1, 'actAjuda', 'Ajuda do sistema', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (51, 1, 'actConfigServidor', 'Configuração do banco de dados', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (52, 1, 'actInfoSistema', 'Informações sobre o sistema', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (53, 1, 'actVendedor', 'Vendedores', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (54, 1, 'actConfigNota', 'Configuração da nota', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (55, 1, 'actPromocao', 'Promoções', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (56, 1, 'actInfoAvisos', 'Informações e avisos', 'S');
INSERT INTO ITEMPERFIL (IDITEMPERFIL, IDPERFIL, ACAO_NOME, ACAO_CAPTION, LIBERADO) VALUES (57, 1, 'actAuditoriaUser', 'Auditoria de registros', 'S');

COMMIT WORK;

set generator GENIDITEMPERFIL to 58;

delete from logerro;
delete from logoperacao;
delete from pagtocompra;
delete from perda;

delete from produtos;
delete from promocao;
delete from recibo;
delete from rectovenda;

update sistema s set
  s.DATAVALIDADE = null,
  s.DATA_ACESSO = null,
  s.SERIAL = null,
  s.HD = null;

delete from unidades;

INSERT INTO UNIDADES (CODUNIDADE, DESCRICAO) VALUES (1, 'UN');
INSERT INTO UNIDADES (CODUNIDADE, DESCRICAO) VALUES (2, 'KG');
INSERT INTO UNIDADES (CODUNIDADE, DESCRICAO) VALUES (3, 'PCT');
INSERT INTO UNIDADES (CODUNIDADE, DESCRICAO) VALUES (4, 'ML');
INSERT INTO UNIDADES (CODUNIDADE, DESCRICAO) VALUES (5, 'GR');

COMMIT WORK;

delete from usuarios;

insert into usuarios values(1,'Usuário padrão','adm','3412',1);
commit work;

delete from vendedor;
