CREATE TABLE AGENDA
(
  IDAGENDA int NOT NULL AUTO_INCREMENT,
  NOME varchar(100),
  TELEFONE varchar(20),
  OBS varchar(255),
  CONSTRAINT PK_AGENDA PRIMARY KEY (IDAGENDA)
);
CREATE TABLE ALIQUOTAS
(
  CODALIQUOTA int NOT NULL AUTO_INCREMENT,
  DESCRICAO varchar(50),
  CONSTRAINT PK_ALIQUOTAS PRIMARY KEY (CODALIQUOTA)
);
CREATE TABLE BANCO
(
  IDBANCO int NOT NULL AUTO_INCREMENT,
  BANCO varchar(100),
  CONSTRAINT PK_BANCO PRIMARY KEY (IDBANCO)
);
CREATE TABLE CAIXA
(
  CODCAIXA int NOT NULL AUTO_INCREMENT,
  CODCAIXAS int NOT NULL,
  DATA_LANC date,
  DESCRICAO varchar(100),
  DOCUMENTO varchar(50),
  TIPO varchar(1),
  VALOR DECIMAL(13,2),
  EXCLUIR varchar(1),
  CONSTRAINT PK_CAIXA PRIMARY KEY (CODCAIXA)
);
CREATE TABLE CAIXAS
(
  CODIGO int NOT NULL AUTO_INCREMENT,
  NOME varchar(100),
  INATIVO varchar(1),
  CONSTRAINT PK_CAIXAS PRIMARY KEY (CODIGO)
);
CREATE TABLE CFOP
(
  id int NOT NULL AUTO_INCREMENT,
  NUMERO varchar(50) NOT NULL,
  OPERACAO varchar(150),
  CFNOTA varchar(255),
  CONSTRAINT PK_CFOP PRIMARY KEY (NUMERO)
);
CREATE TABLE CHEQUE
(
  IDCHEQUE int NOT NULL AUTO_INCREMENT,
  IDBANCO int,
  IDCLIENTE int,
  IDFORN int,
  BANDAMAGNETICA varchar(100),
  AGENCIA varchar(100),
  CONTA varchar(50),
  NUMERO varchar(50),
  DATAEMISSAO date,
  BOMPARA date,
  VALOR DECIMAL(13,2),
  VENDA int,
  COMPRA int,
  REPASSADO varchar(1),
  DATABAIXADO date,
  CONSTRAINT PK_CHEQUE PRIMARY KEY (IDCHEQUE)
);
CREATE TABLE CIDADES
(
  CODCIDADE int NOT NULL AUTO_INCREMENT,
  DESCRICAO varchar(100),
  CONSTRAINT PK_CIDADES PRIMARY KEY (CODCIDADE)
);
CREATE TABLE CLIENTES
(
  CODCLIENTE int NOT NULL AUTO_INCREMENT,
  TIPO varchar(1),
  NOME varchar(100),
  ENDERECO varchar(100),
  CEP varchar(20),
  BAIRRO varchar(100),
  TELEFONE varchar(20),
  FAX varchar(20)
  CODCIDADE int,
  UF varchar(2),
  TEMPO_MORADIA varchar(100),
  END_ANTERIOR varchar(100),
  E_MAIL varchar(100),
  TRABALHO varchar(100),
  CARGO varchar(100),
  DATA_INICIO date,
  SALARIO DECIMAL(13,2),
  ESTADO_CIVIL varchar(1),
  CONJUGUE varchar(100),
  LOCAL_TRAB varchar(100),
  DATA_NASC date,
  PAI varchar(100),
  MAE varchar(100),
  CPF_CNPJ CNPJCPF,
  RG_IE varchar(50),
  REFER_PES varchar(150),
  REFER_COM varchar(150),
  FONE_COM varchar(20)
  CADASTRO date,
  OBS varchar(255),
  NATURALIDADE varchar(100),
  LIMITE DECIMAL(13,2),
  FOTO blob
  CONSTRAINT PK_CLIENTES PRIMARY KEY (CODCLIENTE)
);
CREATE TABLE CONFIGDUPLICATA
(
  id int NOT NULL AUTO_INCREMENT
  CAMPO varchar(100),
  VERTICAL int,
  HORIZONTAL int,
  FONTE int,
  NOMECAMPO varchar(100),
  TIPOFONTE varchar(100),
  ESTILOFONTE varchar(100)
);
CREATE TABLE CONFIGNOTA
(
  CODIGO int NOT NULL AUTO_INCREMENT,
  CAMPO varchar(100),
  LAYOUT varchar(100),
  REFERENCIA varchar(100),
  TIPO varchar(1),
  LINHA int,
  COLUNA int,
  IMPRIMIR varchar(1),
  CONSTRAINT PK_CONFIGNOTA PRIMARY KEY (CODIGO)
);
CREATE TABLE CONFIGURACAO
(
  IDCONFIGURACAO int NOT NULL AUTO_INCREMENT,
  NOMECOMPUTADOR varchar(100),
  BARRAFERRAMENTA varchar(1),
  HINTBALAO varchar(1),
  GRAVAERRO varchar(1),
  BACKUP varchar(1),
  LOG varchar(1),
  IMPRESSORA varchar(1),
  RESOLUCAO varchar(1),
  LETRACODIGOBARRA varchar(1),
  EXIBEDICADIA varchar(1),
  AVISACLIENTEATRASO varchar(1),
  DIREXPORTPADRAO varchar(150),
  SENHAESTOQUE varchar(50),
  USARSENHAESTOQUE varchar(1),
  ESTOQUEPADRAO int,
  BORDAETQPROD varchar(1),
  ALIQUOTAPADRAO int NOT NULL,
  DESCPADRAOPROD DECIMAL(13,2),
  CAIXAPADRAO int NOT NULL,
  SENHACAIXA varchar(50),
  PRODSEMESTOQORCAM varchar(1),
  ORCAMNAOCONC varchar(1),
  EDITORCAMCONC varchar(1),
  COMPRANAOCONC varchar(1),
  EDITCOMPRACONC varchar(1),
  PRODSEMESTOQVENDA varchar(1),
  VENDANAOCONC varchar(1),
  EDITVENDACONC varchar(1),
  BORDAETQCLIENTE varchar(1),
  MOSTRARSALDOCAIXA varchar(1),
  CAIXA90DIAS varchar(1),
  RELZEBRADO varchar(1),
  VERIFICA_UPD varchar(1),
  CONTACHEQUE int,
  INFOAVISOS varchar(1),
  CONSTRAINT PK_CONFIGURACAO PRIMARY KEY (IDCONFIGURACAO)
);
CREATE TABLE CONFIGURACAOGLOBAL
(
  TAXAJURO DECIMAL(13,2),
  INTERVALO int,
  PRAZOINICIAL int,
  PARCELAS int,
  LIMITECLIENTE DECIMAL(13,2),
  TITULOORCAM varchar(100),
  COLUNAORCAMBOBINA int,
  MSGRODAPEORCAM varchar(150),
  TITULOVENDA varchar(100),
  COLUNAVENDABOBINA int,
  MSGRODAPEVENDA varchar(150),
  LINHAPULARBOBINAVENDA int,
  LINHAPULARBOBINAORCAM int,
  PORTAIMPVENDA varchar(50),
  FTP_HOST varchar(100),
  FTP_USER_NAME varchar(100),
  FTP_PASSWORD varchar(100),
  FTP_TIMEOUT int,
  FTP_PASSIVE varchar(1),
  FTP_DIR varchar(100),
  IDADECADASTROCLIENTE int,
  IDCONFIGGLOBAL int NOT NULL AUTO_INCREMENT,
  CONSTRAINT PK_CONFIGURACAOGLOBAL PRIMARY KEY (IDCONFIGGLOBAL)
);
CREATE TABLE CONTASPAGAR
(
  CODIGO int NOT NULL AUTO_INCREMENT,
  DATA date,
  VENCIMENTO date,
  DESCRICAO varchar(100),
  FORNECEDOR int,
  VALOR DECIMAL(13,2),
  DOCUMENTO varchar(50),
  PAGAR varchar(1),
  JURO DECIMAL(13,2),
  PAGA varchar(1),
  DATAPAGTO date,
  ORIGEM int,
  COMPRA int,
  CAPITALPAGO DECIMAL(13,2),
  JUROPAGO DECIMAL(13,2),
  DESCTO DECIMAL(13,2),
  OBS varchar(255),
  IDCONTA int,
  CONSTRAINT PK_CONTASPAGAR PRIMARY KEY (CODIGO)
);
CREATE TABLE CONTASRECEBER
(
  CODIGO int NOT NULL AUTO_INCREMENT,
  DATA date,
  VENCIMENTO date,
  CLIENTE int,
  DESCRICAO varchar(100),
  DOCUMENTO varchar(50),
  VALOR DECIMAL(13,2),
  JURO DECIMAL(13,2),
  RECEBER varchar(1),
  RECDA varchar(1),
  DATARECTO date,
  ORIGEM int,
  VENDA int,
  CAPITALRECDO DECIMAL(13,2),
  JURORECDO DECIMAL(13,2),
  DESCTO DECIMAL(13,2),
  OBS varchar(255),
  IDCONTA int,
  CONSTRAINT PK_CONTASRECEBER PRIMARY KEY (CODIGO)
);
CREATE TABLE DUPLICATA
(
  IDDUPLICATA int NOT NULL AUTO_INCREMENT,
  NRODUPLICATA varchar(50),
  SACADO varchar(100),
  CPF_CNPJ CNPJCPF,
  ENDERECO varchar(100),
  BAIRRO varchar(100),
  CEP varchar(20),
  IDCIDADE int,
  FONEFAX varchar(20)
  UF varchar(2),
  IE varchar(50),
  DATAEMISSAO date,
  NROFATURA varchar(50),
  VALOR_FATURA DECIMAL(13,2),
  VALOR DECIMAL(13,2),
  DATAVENC date,
  DESCONTO DECIMAL(13,2),
  PRACAPAGAMENTO varchar(150),
  DATADESCTO date,
  VALOREXTENSO varchar(150),
  DATAIMPRESSAO date,
  IMPRESSA varchar(1),
  CONSTRAINT PK_DUPLICATA PRIMARY KEY (IDDUPLICATA)
);
CREATE TABLE EMPRESA
(
    id int NOT NULL AUTO_INCREMENT,
  FANTAZIA varchar(100),
  RAZASOCIAL varchar(100),
  CNPJ CNPJCPF,
  IE varchar(50),
  IM varchar(50),
  ENDERECO varchar(100),
  IDCIDADE int,
  BAIRRO varchar(100),
  CEP varchar(20),
  TELEFONE varchar(20),
  FAX varchar(20)
  UF varchar(2),
  RESPONSAVEL varchar(100),
  LOGOEMPRESA blob,
  EMAIL varchar(150)
);
CREATE TABLE ENVELOPE
(
  IDENVELOPE int NOT NULL AUTO_INCREMENT,
  NOME varchar(100),
  ENDERECO varchar(100),
  IDCIDADE int,
  BAIRRO varchar(100),
  CEP varchar(20),
  MENSAGEM varchar(150),
  CONSTRAINT PK_ENVELOPE PRIMARY KEY (IDENVELOPE)
);
CREATE TABLE ETIQUETA
(
  IDETIQUETA int NOT NULL AUTO_INCREMENT,
  ETIQUETA varchar(100),
  ALTURAFOLHA decimal(13,2),
  LARGURAFOLHA decimal(13,2),
  MARGEMSUPERIOR decimal(13,2),
  MARGEMESQUERDA decimal(13,2),
  NUMEROLINHAS int,
  NUMEROCOLUNAS int,
  ALTURAETIQUETA decimal(13,2),
  LARGURAETIQUETA decimal(13,2),
  DISTANCIAVERTICAL decimal(13,2),
  DISTANCIAHORIZONTAL decimal(13,2),
  DISTACOLVERTICAL decimal(13,2),
  DISTCOLHORIZ decimal(13,2),
  CONSTRAINT PK_ETIQUETA PRIMARY KEY (IDETIQUETA)
);
CREATE TABLE ETIQUETAPROD
(
  IDETIQUETAPROD int NOT NULL AUTO_INCREMENT,
  CODBARRA varchar(255),
  DESCRICAO varchar(100),
  PRECO DECIMAL(13,2),
  CONSTRAINT PK_ETIQUETAPROD PRIMARY KEY (IDETIQUETAPROD)
);
CREATE TABLE FORNECEDORES
(
  CODFORNECEDOR int NOT NULL AUTO_INCREMENT,
  FANTAZIA varchar(100),
  RAZAOSOCIAL varchar(100),
  DATACAD date,
  ENDERECO varchar(100),
  CIDADE int,
  BAIRRO varchar(100),
  CNPJ CNPJCPF,
  IE varchar(50),
  CEP varchar(20),
  TELEFONE varchar(20),
  FAX varchar(20)
  EMAIL varchar(100),
  UF varchar(2),
  OBS varchar(255),
  VENDEDOR varchar(100),
  TELEFONEVENDEDOR varchar(20)
  EMAILVENDEDOR varchar(100),
  TIPO varchar(1),
  CONSTRAINT PK_FORNECEDORES PRIMARY KEY (CODFORNECEDOR)
);
CREATE TABLE GRUPOS
(
  CODGRUPO int NOT NULL AUTO_INCREMENT,
  DESCRICAO varchar(100),
  CONSTRAINT PK_GRUPOS PRIMARY KEY (CODGRUPO)
);
CREATE TABLE ITEMNOTAFISCAL
(
  NUMERO int NOT NULL AUTO_INCREMENT,
  PRODUTO int,
  ALIQUOTA int,
  QTDE int,
  TOTAL DECIMAL(13,2),
  CUSTO DECIMAL(13,2),
  LUCRO int,
  VENDA DECIMAL(13,2),
  IPI DECIMAL(13,2),
  DESCONTO DECIMAL(13,2)
);
CREATE TABLE ITEMORCAMENTO
(
  CODIGO int NOT NULL AUTO_INCREMENT,
  CODPRODUTO int,
  QTDE int,
  CUSTO DECIMAL(13,2),
  VENDA DECIMAL(13,2),
  DESCTO DECIMAL(13,2),
  VALORDESCTO DECIMAL(13,2),
  TOTAL DECIMAL(13,2)
);
CREATE TABLE ITEMPERFIL
(
  IDITEMPERFIL int NOT NULL AUTO_INCREMENT,
  IDPERFIL int NOT NULL,
  ACAO_NOME varchar(100),
  ACAO_CAPTION varchar(100),
  LIBERADO varchar(1),
  CONSTRAINT PK_ITEMPERFIL PRIMARY KEY (IDITEMPERFIL)
);
CREATE TABLE ITEMVENDA
(
  CODIGO int NOT NULL AUTO_INCREMENT,
  CODPRODUTO int,
  QTD int,
  CUSTO DECIMAL(13,2),
  VENDA DECIMAL(13,2),
  DESCTO DECIMAL(13,2),
  VALORDESCTO DECIMAL(13,2),
  TOTAL DECIMAL(13,2),
  COMISSAO DECIMAL(13,2),
  VALORCOMISSAO DECIMAL(13,2)
);
CREATE TABLE LOGERRO
(
  IDLOGERRO int NOT NULL AUTO_INCREMENT,
  DATAHORA datetime,
  FORM varchar(100),
  CONTROLE varchar(100),
  MSG varchar(150),
  CONSTRAINT PK_LOGERRO PRIMARY KEY (IDLOGERRO)
);
CREATE TABLE LOGOPERACAO
(
  IDLOGOPERACAO int NOT NULL AUTO_INCREMENT,
  IDCONNECTION int,
  ORIGEM varchar(100),
  USUARIO LOGIN,
  DATAHORA datetime,
  ABERTO varchar(1),
  CONSTRAINT PK_LOGOPERACAO PRIMARY KEY (IDLOGOPERACAO)
);
CREATE TABLE MENSAGEM
(
  IDMENSAGEM int NOT NULL AUTO_INCREMENT,
  MENSAGEM MSG,
  DATA_CADASTRO date,
  TIPO varchar(1),
  IDWEB int,
  CONSTRAINT PK_MENSAGEM PRIMARY KEY (IDMENSAGEM)
);
CREATE TABLE NOTAS_FISCAIS
(
  NUMERO int NOT NULL AUTO_INCREMENT,
  CODFORNECEDOR int,
  DATANOTA date,
  DATAENTRADA date,
  CFOP varchar(50),
  DESCONTO DECIMAL(13,2),
  ICMS DECIMAL(13,2),
  IPI DECIMAL(13,2),
  FRETE DECIMAL(13,2),
  DESPESAS DECIMAL(13,2),
  TOTALPRODUTO DECIMAL(13,2),
  TOTAL DECIMAL(13,2),
  OBS varchar(255),
  BAIXADO varchar(1),
  CONCLUIDA varchar(1),
  CANCELADO varchar(1),
  CONSTRAINT PK_NOTAS_FISCAIS PRIMARY KEY (NUMERO)
);
CREATE TABLE ORCAMENTO
(
  CODIGO int NOT NULL AUTO_INCREMENT,
  IDVENDEDOR int,
  CODCLIENTE int,
  DATA date,
  OBS varchar(150),
  TOTAL DECIMAL(13,2),
  ITENS int,
  STATUS varchar(1),
  CONCLUIDO varchar(1),
  CONSTRAINT PK_ORCAMENTO PRIMARY KEY (CODIGO)
);
CREATE TABLE PAGTOCOMPRA
(
  IDPAGTOCOMPRA int NOT NULL AUTO_INCREMENT,
  IDCOMPRA int,
  DATAPAGTO date,
  FORMAPAGTO varchar(50),
  VALORPAGO DECIMAL(13,2),
  VALORRESTO DECIMAL(13,2),
  CONSTRAINT PK_PAGTOCOMPRA PRIMARY KEY (IDPAGTOCOMPRA)
);
CREATE TABLE PERDA
(
  CODIGO int NOT NULL AUTO_INCREMENT,
  CODPRODUTO int,
  QTDE int,
  PRECO DECIMAL(13,2),
  DATA date,
  MOTIVO varchar(1),
  OBS varchar(255),
  CONSTRAINT PK_PERDA PRIMARY KEY (CODIGO)
);
CREATE TABLE PERFIL
(
  IDPERFIL int NOT NULL AUTO_INCREMENT,
  PERFIL varchar(100),
  CONSTRAINT PK_PERFIL PRIMARY KEY (IDPERFIL)
);
CREATE TABLE PRODUTOS
(
  IDPRODUTO int NOT NULL AUTO_INCREMENT,
  CODBARRA varchar(255),
  REFERENCIA varchar(50),
  CODFORNECEDOR int,
  CODGRUPO int,
  DESCRICAO varchar(100),
  ABREVIACAO varchar(100),
  DATAVALIDADE date,
  CODUNIDADE int,
  PESO DECIMAL(13,2),
  PRECO_PROMOCAO DECIMAL(13,2),
  CUSTO DECIMAL(13,2),
  LUCRO DECIMAL(13,2),
  VENDA DECIMAL(13,2),
  ESTOQUE int,
  ESTOQUEMINIMO int,
  IDALIQUOTA int,
  NOVO varchar(1),
  ALTERADO varchar(1),
  QTDERECEBIDA int,
  DATARECEBIDA date,
  EXCLUIR varchar(1),
  PROMOCAO varchar(1),
  OBS varchar(255),
  CONSTRAINT PK_PRODUTOS PRIMARY KEY (IDPRODUTO)
);
CREATE TABLE PROMOCAO
(
  CODIGO int NOT NULL AUTO_INCREMENT,
  PRODUTO int NOT NULL,
  DESCONTO DECIMAL(13,2),
  PRECO DECIMAL(13,2),
  INICIO date,
  FIM date,
  CONSTRAINT PK_PROMOCAO PRIMARY KEY (CODIGO),
  CONSTRAINT UN_PROMOCAO_PRODUTO UNIQUE (PRODUTO)
);
CREATE TABLE RECIBO
(
  IDRECIBO int NOT NULL AUTO_INCREMENT,
  DATA date,
  RECEBEDOR varchar(150),
  REFERENTE varchar(255),
  VALOR DECIMAL(13,2),
  VALOREXTENSO varchar(255),
  CONSTRAINT PK_RECIBO PRIMARY KEY (IDRECIBO)
);
CREATE TABLE RECTOVENDA
(
  IDRECTOVENDA int NOT NULL AUTO_INCREMENT,
  IDVENDA int,
  DATARECTO date,
  FORMARECTO varchar(50),
  VALORRECDO DECIMAL(13,2),
  VALORRESTO DECIMAL(13,2),
  CONSTRAINT PK_RECTOVENDA PRIMARY KEY (IDRECTOVENDA)
);
CREATE TABLE SISTEMA
(
  IDSISTEMA int NOT NULL AUTO_INCREMENT,
  VERSAO varchar(50),
  DATAVALIDADE date,
  DATA_ACESSO date,
  SERIAL varchar(30),
  HD varchar(50),
  CONSTRAINT PK_SISTEMA PRIMARY KEY (IDSISTEMA)
);
CREATE TABLE UNIDADES
(
  CODUNIDADE int NOT NULL AUTO_INCREMENT,
  DESCRICAO varchar(50),
  CONSTRAINT PK_UNIDADES PRIMARY KEY (CODUNIDADE)
);
CREATE TABLE USUARIOS
(
  IDUSUARIOS int NOT NULL AUTO_INCREMENT,
  NOME varchar(100),
  LOGIN LOGIN NOT NULL,
  SENHA varchar(50),
  IDPERFIL int,
  CONSTRAINT PK_USUARIOS PRIMARY KEY (IDUSUARIOS)
);
CREATE TABLE VENDA
(
  CODIGO int NOT NULL AUTO_INCREMENT,
  IDVENDEDOR int,
  CODCLIENTE int,
  DATA date,
  OBS varchar(150),
  TOTALDESCTO DECIMAL(13,2),
  TOTAL DECIMAL(13,2),
  CONCLUIDA varchar(1),
  BAIXADO varchar(1),
  CANCELADO varchar(1),
  CONSTRAINT PK_VENDA PRIMARY KEY (CODIGO)
);
CREATE TABLE VENDEDOR
(
  IDVENDEDOR int NOT NULL AUTO_INCREMENT,
  VENDEDOR varchar(100),
  ATIVO varchar(1),
  CONSTRAINT PK_VENDEDOR PRIMARY KEY (IDVENDEDOR)
);


ALTER TABLE CAIXA ADD CONSTRAINT FK_CAIXA_CAIXAS
  FOREIGN KEY (CODCAIXAS) REFERENCES CAIXAS (CODIGO) ON UPDATE SET NULL ON DELETE SET NULL;
CREATE INDEX IDX_CAIXA_DATA ON CAIXA (DATA);
ALTER TABLE CHEQUE ADD CONSTRAINT FK_CHEQUE_BANCO
  FOREIGN KEY (IDBANCO) REFERENCES BANCO (IDBANCO) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CHEQUE ADD CONSTRAINT FK_CHEQUE_CLIENTE
  FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES (CODCLIENTE) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CHEQUE ADD CONSTRAINT FK_CHEQUE_COMPRA
  FOREIGN KEY (COMPRA) REFERENCES NOTAS_FISCAIS (NUMERO) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CHEQUE ADD CONSTRAINT FK_CHEQUE_FORN
  FOREIGN KEY (IDFORN) REFERENCES FORNECEDORES (CODFORNECEDOR) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CHEQUE ADD CONSTRAINT FK_CHEQUE_VENDA
  FOREIGN KEY (VENDA) REFERENCES VENDA (CODIGO) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_CIDADE
  FOREIGN KEY (CODCIDADE) REFERENCES CIDADES (CODCIDADE);
ALTER TABLE CONFIGURACAO ADD CONSTRAINT FK_CONFIGURACAO_ALIQUOTA
  FOREIGN KEY (ALIQUOTAPADRAO) REFERENCES ALIQUOTAS (CODALIQUOTA) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CONFIGURACAO ADD CONSTRAINT FK_CONFIGURACAO_CAIXA
  FOREIGN KEY (CAIXAPADRAO) REFERENCES CAIXAS (CODIGO) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CONFIGURACAO ADD CONSTRAINT FK_CONFIGURACAO_CONTACAIXA
  FOREIGN KEY (CONTACHEQUE) REFERENCES CAIXAS (CODIGO) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE CONTASPAGAR ADD CONSTRAINT FK_CONTASPAGAR_CONTA
  FOREIGN KEY (IDCONTA) REFERENCES CAIXAS (CODIGO);
ALTER TABLE CONTASPAGAR ADD CONSTRAINT FK_CONTASPAGAR_FORN
  FOREIGN KEY (FORNECEDOR) REFERENCES FORNECEDORES (CODFORNECEDOR);
ALTER TABLE CONTASRECEBER ADD CONSTRAINT FK_CONTASRECEBER_CLIENTE
  FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (CODCLIENTE);
ALTER TABLE CONTASRECEBER ADD CONSTRAINT FK_CONTASRECEBER_CONTA
  FOREIGN KEY (IDCONTA) REFERENCES CAIXAS (CODIGO);
ALTER TABLE DUPLICATA ADD CONSTRAINT FK_DUPLICATA_CIDADE
  FOREIGN KEY (IDCIDADE) REFERENCES CIDADES (CODCIDADE);
ALTER TABLE EMPRESA ADD CONSTRAINT FK_EMPRESA_CIDADE
  FOREIGN KEY (IDCIDADE) REFERENCES CIDADES (CODCIDADE);
ALTER TABLE ENVELOPE ADD CONSTRAINT FK_ENVELOPE_CIDADE
  FOREIGN KEY (IDCIDADE) REFERENCES CIDADES (CODCIDADE);
ALTER TABLE FORNECEDORES ADD CONSTRAINT FK_FORNECEDORES_CIDADE
  FOREIGN KEY (CIDADE) REFERENCES CIDADES (CODCIDADE);
ALTER TABLE ITEMNOTAFISCAL ADD CONSTRAINT FK_ITEMNOTAFISCAL_ALIQUOTA
  FOREIGN KEY (ALIQUOTA) REFERENCES ALIQUOTAS (CODALIQUOTA);
ALTER TABLE ITEMNOTAFISCAL ADD CONSTRAINT FK_ITEMNOTAFISCAL_NOTAFISCAL
  FOREIGN KEY (NUMERO) REFERENCES NOTAS_FISCAIS (NUMERO);
ALTER TABLE ITEMNOTAFISCAL ADD CONSTRAINT FK_ITEMNOTAFISCAL_PRODUTO
  FOREIGN KEY (PRODUTO) REFERENCES PRODUTOS (IDPRODUTO);
ALTER TABLE ITEMORCAMENTO ADD CONSTRAINT FK_ITEMORCAMENTO_ORCAM
  FOREIGN KEY (CODIGO) REFERENCES ORCAMENTO (CODIGO);
ALTER TABLE ITEMORCAMENTO ADD CONSTRAINT FK_ITEMORCAMENTO_PRODUTO
  FOREIGN KEY (CODPRODUTO) REFERENCES PRODUTOS (IDPRODUTO);
ALTER TABLE ITEMPERFIL ADD CONSTRAINT FK_ITEMPERFIL_PERFIL
  FOREIGN KEY (IDPERFIL) REFERENCES PERFIL (IDPERFIL) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE ITEMVENDA ADD CONSTRAINT FK_ITEMVENDA_PRODUTO
  FOREIGN KEY (CODPRODUTO) REFERENCES PRODUTOS (IDPRODUTO);
ALTER TABLE ITEMVENDA ADD CONSTRAINT FK_ITEMVENDA_VENDA
  FOREIGN KEY (CODIGO) REFERENCES VENDA (CODIGO);
ALTER TABLE NOTAS_FISCAIS ADD CONSTRAINT FK_NOTAS_FISCAIS_FORN
  FOREIGN KEY (CODFORNECEDOR) REFERENCES FORNECEDORES (CODFORNECEDOR);
ALTER TABLE ORCAMENTO ADD CONSTRAINT FK_ORCAMENTO_CLIENTE
  FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTES (CODCLIENTE);
ALTER TABLE ORCAMENTO ADD CONSTRAINT FK_ORCAMENTO_VENDEDOR
  FOREIGN KEY (IDVENDEDOR) REFERENCES VENDEDOR (IDVENDEDOR);
ALTER TABLE PAGTOCOMPRA ADD CONSTRAINT FK_PAGTOCOMPRA_COMPRA
  FOREIGN KEY (IDCOMPRA) REFERENCES NOTAS_FISCAIS (NUMERO) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE PERDA ADD CONSTRAINT FK_PERDA_PRODUTO
  FOREIGN KEY (CODPRODUTO) REFERENCES PRODUTOS (IDPRODUTO);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_ALIQUOTA
  FOREIGN KEY (IDALIQUOTA) REFERENCES ALIQUOTAS (CODALIQUOTA);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_FORN
  FOREIGN KEY (CODFORNECEDOR) REFERENCES FORNECEDORES (CODFORNECEDOR);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_GRUPO
  FOREIGN KEY (CODGRUPO) REFERENCES GRUPOS (CODGRUPO);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_UNIDADE
  FOREIGN KEY (CODUNIDADE) REFERENCES UNIDADES (CODUNIDADE);
ALTER TABLE PROMOCAO ADD CONSTRAINT FK_PROMOCAO_PRODUTO
  FOREIGN KEY (PRODUTO) REFERENCES PRODUTOS (IDPRODUTO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE RECTOVENDA ADD CONSTRAINT FK_RECTOVENDA_VENDA
  FOREIGN KEY (IDVENDA) REFERENCES VENDA (CODIGO) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_PERFIL
  FOREIGN KEY (IDPERFIL) REFERENCES PERFIL (IDPERFIL) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_CLIENTE
  FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTES (CODCLIENTE);
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_VENDEDOR
  FOREIGN KEY (IDVENDEDOR) REFERENCES VENDEDOR (IDVENDEDOR);

  ALTER TABLE wscd.CONFIGURACAO ADD NCONTACHEQUE varchar(100) NULL;

drop table ALIQUOTAS;
drop table CFOP;
drop table CONFIGDUPLICATA;
drop table CONFIGNOTA;
drop table DUPLICATA;
drop table ENVELOPE;
drop table ITEMPERFIL;
drop table LOGERRO;
drop table LOGOPERACAO;
drop table MENSAGEM;

