CREATE TABLE AGENDA
(
  IDAGENDA int NOT NULL AUTO_INCREMENT,
  NOME varchar(100),
  TELEFONE varchar(20),
  OBS varchar(255),
  CONSTRAINT PK_AGENDA PRIMARY KEY (IDAGENDA)
);
CREATE TABLE BANCO
(
  IDBANCO int NOT NULL AUTO_INCREMENT,
  BANCO varchar(100),
  CONSTRAINT PK_BANCO PRIMARY KEY (IDBANCO)
);
CREATE TABLE CAIXA
(
  CODCAIXA int NOT NULL AUTO_INCREMENT,
  CODCAIXAS int NOT NULL,
  DATA_LANC date,
  DESCRICAO varchar(100),
  DOCUMENTO varchar(50),
  TIPO varchar(1),
  VALOR DECIMAL(13,2),
  EXCLUIR varchar(1),
  CONSTRAINT PK_CAIXA PRIMARY KEY (CODCAIXA)
);
CREATE TABLE CAIXAS
(
  CODIGO int NOT NULL AUTO_INCREMENT,
  NOME varchar(100),
  INATIVO varchar(1),
  CONSTRAINT PK_CAIXAS PRIMARY KEY (CODIGO)
);
CREATE TABLE CIDADES
(
  CODCIDADE int NOT NULL AUTO_INCREMENT,
  DESCRICAO varchar(100),
  CONSTRAINT PK_CIDADES PRIMARY KEY (CODCIDADE)
);
CREATE TABLE CLIENTES
(
  CODCLIENTE int NOT NULL AUTO_INCREMENT,
  TIPO varchar(1),
  NOME varchar(100),
  ENDERECO varchar(100),
  CEP varchar(20),
  BAIRRO varchar(100),
  TELEFONE varchar(20),
  CODCIDADE int,
  UF varchar(2),
  E_MAIL varchar(100),
  CPF_CNPJ varchar(30),
  RG_IE varchar(50),
  REFER_PES varchar(150),
  REFER_COM varchar(150),
  FONE_COM varchar(20),
  CADASTRO date,
  OBS varchar(255),
  CONSTRAINT PK_CLIENTES PRIMARY KEY (CODCLIENTE)
);
CREATE TABLE CONFIGURACAO
(
  IDCONFIGURACAO int NOT NULL AUTO_INCREMENT,
  NOMECOMPUTADOR varchar(100),
  CAIXAPADRAO int NOT NULL,
  SENHACAIXA varchar(50),
  MOSTRARSALDOCAIXA varchar(1),
  CAIXA90DIAS varchar(1),
  RELZEBRADO varchar(1),
  CONSTRAINT PK_CONFIGURACAO PRIMARY KEY (IDCONFIGURACAO)
);
CREATE TABLE CONTASPAGAR
(
  CODIGO int NOT NULL AUTO_INCREMENT,
  DATA date,
  VENCIMENTO date,
  DESCRICAO varchar(100),
  FORNECEDOR int,
  VALOR DECIMAL(13,2),
  DOCUMENTO varchar(50),
  PAGAR varchar(1),
  JURO DECIMAL(13,2),
  PAGA varchar(1),
  DATAPAGTO date,
  ORIGEM int,
  COMPRA int,
  CAPITALPAGO DECIMAL(13,2),
  JUROPAGO DECIMAL(13,2),
  DESCTO DECIMAL(13,2),
  OBS varchar(255),
  IDCONTA int,
  CONSTRAINT PK_CONTASPAGAR PRIMARY KEY (CODIGO)
);
CREATE TABLE CONTASRECEBER
(
  CODIGO int NOT NULL AUTO_INCREMENT,
  DATA date,
  VENCIMENTO date,
  CLIENTE int,
  DESCRICAO varchar(100),
  DOCUMENTO varchar(50),
  VALOR DECIMAL(13,2),
  JURO DECIMAL(13,2),
  RECEBER varchar(1),
  RECDA varchar(1),
  DATARECTO date,
  ORIGEM int,
  VENDA int,
  CAPITALRECDO DECIMAL(13,2),
  JURORECDO DECIMAL(13,2),
  DESCTO DECIMAL(13,2),
  OBS varchar(255),
  IDCONTA int,
  CONSTRAINT PK_CONTASRECEBER PRIMARY KEY (CODIGO)
);
CREATE TABLE EMPRESA
(
  ID int NOT NULL AUTO_INCREMENT,
  FANTASIA varchar(100),
  RAZASOCIAL varchar(100),
  CNPJ varchar(30),
  IE varchar(50),
  IM varchar(50),
  ENDERECO varchar(100),
  IDCIDADE int,
  BAIRRO varchar(100),
  CEP varchar(20),
  TELEFONE varchar(20),
  FAX varchar(20),
  UF varchar(2),
  RESPONSAVEL varchar(100),
  LOGOEMPRESA blob,
  EMAIL varchar(150),
  CONSTRAINT PK_EMPRESA PRIMARY KEY (ID)
);
CREATE TABLE ENVELOPE
(
  IDENVELOPE int NOT NULL AUTO_INCREMENT,
  NOME varchar(100),
  ENDERECO varchar(100),
  IDCIDADE int,
  BAIRRO varchar(100),
  CEP varchar(20),
  MENSAGEM varchar(150),
  CONSTRAINT PK_ENVELOPE PRIMARY KEY (IDENVELOPE)
);
CREATE TABLE ETIQUETA
(
  IDETIQUETA int NOT NULL AUTO_INCREMENT,
  ETIQUETA varchar(100),
  ALTURAFOLHA decimal(13,2),
  LARGURAFOLHA decimal(13,2),
  MARGEMSUPERIOR decimal(13,2),
  MARGEMESQUERDA decimal(13,2),
  NUMEROLINHAS int,
  NUMEROCOLUNAS int,
  ALTURAETIQUETA decimal(13,2),
  LARGURAETIQUETA decimal(13,2),
  DISTANCIAVERTICAL decimal(13,2),
  DISTANCIAHORIZONTAL decimal(13,2),
  DISTACOLVERTICAL decimal(13,2),
  DISTCOLHORIZ decimal(13,2),
  CONSTRAINT PK_ETIQUETA PRIMARY KEY (IDETIQUETA)
);
CREATE TABLE FORNECEDORES
(
  CODFORNECEDOR int NOT NULL AUTO_INCREMENT,
  FANTASIA varchar(100),
  RAZAOSOCIAL varchar(100),
  DATACAD date,
  ENDERECO varchar(100),
  CIDADE int,
  BAIRRO varchar(100),
  CNPJ varchar(30),
  IE varchar(50),
  CEP varchar(20),
  TELEFONE varchar(20),
  FAX varchar(20),
  EMAIL varchar(100),
  UF varchar(2),
  OBS varchar(255),
  VENDEDOR varchar(100),
  TELEFONEVENDEDOR varchar(20),
  EMAILVENDEDOR varchar(100),
  TIPO varchar(1),
  CONSTRAINT PK_FORNECEDORES PRIMARY KEY (CODFORNECEDOR)
);
CREATE TABLE PERFIL
(
  IDPERFIL int NOT NULL AUTO_INCREMENT,
  PERFIL varchar(100),
  CONSTRAINT PK_PERFIL PRIMARY KEY (IDPERFIL)
);
CREATE TABLE RECIBO
(
  IDRECIBO int NOT NULL AUTO_INCREMENT,
  DATA date,
  RECEBEDOR varchar(150),
  REFERENTE varchar(255),
  VALOR DECIMAL(13,2),
  VALOREXTENSO varchar(255),
  CONSTRAINT PK_RECIBO PRIMARY KEY (IDRECIBO)
);
CREATE TABLE SISTEMA
(
  IDSISTEMA int NOT NULL AUTO_INCREMENT,
  VERSAO varchar(50),
  DATAVALIDADE date,
  DATA_ACESSO date,
  SERIAL varchar(30),
  HD varchar(50),
  CONSTRAINT PK_SISTEMA PRIMARY KEY (IDSISTEMA)
);
CREATE TABLE USUARIOS
(
  IDUSUARIOS int NOT NULL AUTO_INCREMENT,
  NOME varchar(100),
  LOGIN varchar(255) NOT NULL,
  SENHA varchar(50),
  IDPERFIL int,
  CONSTRAINT PK_USUARIOS PRIMARY KEY (IDUSUARIOS)
);


ALTER TABLE CAIXA ADD CONSTRAINT FK_CAIXA_CAIXAS
  FOREIGN KEY (CODCAIXAS) REFERENCES CAIXAS (CODIGO) ON UPDATE SET NULL ON DELETE SET NULL;
 
CREATE INDEX IDX_CAIXA_DATA ON CAIXA (DATA_LANC);

ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_CIDADE
  FOREIGN KEY (CODCIDADE) REFERENCES CIDADES (CODCIDADE);
 
ALTER TABLE CONTASPAGAR ADD CONSTRAINT FK_CONTASPAGAR_CONTA
  FOREIGN KEY (IDCONTA) REFERENCES CAIXAS (CODIGO);
 
ALTER TABLE CONTASPAGAR ADD CONSTRAINT FK_CONTASPAGAR_FORN
  FOREIGN KEY (FORNECEDOR) REFERENCES FORNECEDORES (CODFORNECEDOR);
 
ALTER TABLE CONTASRECEBER ADD CONSTRAINT FK_CONTASRECEBER_CLIENTE
  FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (CODCLIENTE);
 
ALTER TABLE CONTASRECEBER ADD CONSTRAINT FK_CONTASRECEBER_CONTA
  FOREIGN KEY (IDCONTA) REFERENCES CAIXAS (CODIGO);
 
ALTER TABLE EMPRESA ADD CONSTRAINT FK_EMPRESA_CIDADE
  FOREIGN KEY (IDCIDADE) REFERENCES CIDADES (CODCIDADE);
 
ALTER TABLE ENVELOPE ADD CONSTRAINT FK_ENVELOPE_CIDADE
  FOREIGN KEY (IDCIDADE) REFERENCES CIDADES (CODCIDADE);
 
ALTER TABLE FORNECEDORES ADD CONSTRAINT FK_FORNECEDORES_CIDADE
  FOREIGN KEY (CIDADE) REFERENCES CIDADES (CODCIDADE);
 
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_PERFIL
  FOREIGN KEY (IDPERFIL) REFERENCES PERFIL (IDPERFIL) ON UPDATE SET NULL ON DELETE SET NULL;

