begin;

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create type party_type as enum ('individual', 'company');
create type cash_entry_type as enum ('credit', 'debit');
create type receivable_origin_type as enum ('sale', 'manual', 'other');
create type payable_origin_type as enum ('purchase', 'manual', 'other');
create type quotation_status as enum ('draft', 'sent', 'approved', 'rejected', 'converted', 'expired');
create type purchase_status as enum ('draft', 'posted', 'completed', 'canceled');
create type sale_status as enum ('draft', 'posted', 'completed', 'canceled');
create type settlement_method as enum ('cash', 'pix', 'card', 'bank_transfer', 'check', 'credit_account', 'other');
create type loss_reason as enum ('expiration', 'damage', 'internal_use', 'adjustment', 'other');

create table organizations (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table app_users (
  id bigint generated by default as identity primary key,
  external_auth_id text not null unique,
  email text,
  full_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table organization_memberships (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  app_user_id bigint not null references app_users(id) on delete cascade,
  role text not null default 'owner',
  created_at timestamptz not null default now(),
  unique (organization_id, app_user_id)
);

create table cities (
  id bigint generated by default as identity primary key,
  name text not null,
  state_code varchar(2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (name, state_code)
);

create table product_groups (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, name)
);

create table units (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  name text not null,
  abbreviation text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, name)
);

create table tax_rates (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  name text not null,
  rate_percent numeric(7,4),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, name)
);

create table cfop_codes (
  code varchar(10) primary key,
  operation_name text,
  note_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table banks (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, name)
);

create table cash_accounts (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  name text not null,
  is_inactive boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, name)
);

create table vendors (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, name)
);

create table customers (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  party_type party_type not null default 'individual',
  name text not null,
  document_number text,
  state_registration text,
  email text,
  phone text,
  address_line text,
  neighborhood text,
  city_id bigint references cities(id),
  state_code varchar(2),
  zip_code text,
  birth_date date,
  credit_limit numeric(14,2) not null default 0,
  notes text,
  is_active boolean not null default true,
  legacy_code integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table suppliers (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  trade_name text not null,
  legal_name text,
  document_number text,
  state_registration text,
  email text,
  phone text,
  address_line text,
  neighborhood text,
  city_id bigint references cities(id),
  state_code varchar(2),
  zip_code text,
  sales_contact_name text,
  sales_contact_phone text,
  sales_contact_email text,
  notes text,
  is_active boolean not null default true,
  legacy_code integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table products (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  barcode text,
  reference text,
  name text not null,
  short_name text,
  supplier_id bigint references suppliers(id),
  group_id bigint references product_groups(id),
  unit_id bigint references units(id),
  tax_rate_id bigint references tax_rates(id),
  expiration_date date,
  weight numeric(14,3),
  cost_price numeric(14,2) not null default 0,
  markup_percent numeric(8,4) not null default 0,
  sale_price numeric(14,2) not null default 0,
  promo_price numeric(14,2),
  current_stock numeric(14,3) not null default 0,
  minimum_stock numeric(14,3) not null default 0,
  received_quantity numeric(14,3) not null default 0,
  received_date date,
  is_promo_active boolean not null default false,
  is_archived boolean not null default false,
  notes text,
  legacy_code integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table company_profiles (
  organization_id bigint primary key references organizations(id) on delete cascade,
  trade_name text,
  legal_name text,
  document_number text,
  state_registration text,
  municipal_registration text,
  email text,
  phone text,
  fax text,
  address_line text,
  neighborhood text,
  city_id bigint references cities(id),
  state_code varchar(2),
  zip_code text,
  responsible_name text,
  logo_asset_url text,
  updated_at timestamptz not null default now()
);

create table business_settings (
  organization_id bigint primary key references organizations(id) on delete cascade,
  default_interest_rate numeric(7,4) not null default 0,
  default_payment_interval_days integer not null default 30,
  default_first_due_days integer not null default 30,
  default_installment_count integer not null default 1,
  default_customer_credit_limit numeric(14,2) not null default 0,
  default_tax_rate_id bigint references tax_rates(id),
  default_product_stock numeric(14,3) not null default 0,
  default_product_discount numeric(14,2) not null default 0,
  default_cash_account_id bigint references cash_accounts(id),
  default_check_cash_account_id bigint references cash_accounts(id),
  quotation_requires_stock boolean not null default false,
  sale_requires_stock boolean not null default true,
  warn_on_open_quotations boolean not null default true,
  warn_on_open_sales boolean not null default true,
  warn_on_open_purchases boolean not null default true,
  reports_zebra_striping boolean not null default true,
  quotation_title text,
  quotation_footer_text text,
  sale_title text,
  sale_footer_text text,
  updated_at timestamptz not null default now()
);

create table quotations (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  customer_id bigint references customers(id),
  vendor_id bigint references vendors(id),
  quotation_date date not null default current_date,
  status quotation_status not null default 'draft',
  is_completed boolean not null default false,
  notes text,
  item_count integer not null default 0,
  total_amount numeric(14,2) not null default 0,
  converted_sale_id bigint,
  legacy_code integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table quotation_items (
  id bigint generated by default as identity primary key,
  quotation_id bigint not null references quotations(id) on delete cascade,
  product_id bigint not null references products(id),
  quantity numeric(14,3) not null check (quantity > 0),
  cost_price_snapshot numeric(14,2) not null default 0,
  sale_price_snapshot numeric(14,2) not null default 0,
  discount_percent numeric(8,4) not null default 0,
  discount_amount numeric(14,2) not null default 0,
  total_amount numeric(14,2) not null default 0,
  display_order integer not null default 0
);

create table sales (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  customer_id bigint references customers(id),
  vendor_id bigint references vendors(id),
  quotation_id bigint references quotations(id),
  sale_date date not null default current_date,
  status sale_status not null default 'draft',
  notes text,
  total_discount numeric(14,2) not null default 0,
  total_amount numeric(14,2) not null default 0,
  is_stock_posted boolean not null default false,
  is_completed boolean not null default false,
  is_canceled boolean not null default false,
  completed_at timestamptz,
  canceled_at timestamptz,
  legacy_code integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table quotations
  add constraint fk_quotations_converted_sale
  foreign key (converted_sale_id) references sales(id) on delete set null;

create table sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references sales(id) on delete cascade,
  product_id bigint not null references products(id),
  quantity numeric(14,3) not null check (quantity > 0),
  cost_price_snapshot numeric(14,2) not null default 0,
  sale_price_snapshot numeric(14,2) not null default 0,
  discount_percent numeric(8,4) not null default 0,
  discount_amount numeric(14,2) not null default 0,
  total_amount numeric(14,2) not null default 0,
  commission_percent numeric(8,4) not null default 0,
  commission_amount numeric(14,2) not null default 0,
  display_order integer not null default 0
);

create table sale_receipts (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references sales(id) on delete cascade,
  receipt_date date not null,
  settlement_method settlement_method not null,
  amount_received numeric(14,2) not null check (amount_received >= 0),
  remaining_amount numeric(14,2) not null check (remaining_amount >= 0),
  notes text,
  created_at timestamptz not null default now()
);

create table purchases (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  supplier_id bigint references suppliers(id),
  issue_date date,
  entry_date date not null default current_date,
  cfop_code varchar(10) references cfop_codes(code),
  discount_amount numeric(14,2) not null default 0,
  icms_amount numeric(14,2) not null default 0,
  ipi_amount numeric(14,2) not null default 0,
  freight_amount numeric(14,2) not null default 0,
  other_costs_amount numeric(14,2) not null default 0,
  items_total numeric(14,2) not null default 0,
  total_amount numeric(14,2) not null default 0,
  notes text,
  status purchase_status not null default 'draft',
  is_stock_posted boolean not null default false,
  is_completed boolean not null default false,
  is_canceled boolean not null default false,
  completed_at timestamptz,
  canceled_at timestamptz,
  legacy_number integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table purchase_items (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references purchases(id) on delete cascade,
  product_id bigint not null references products(id),
  tax_rate_id bigint references tax_rates(id),
  quantity numeric(14,3) not null check (quantity > 0),
  total_amount numeric(14,2) not null default 0,
  cost_price_snapshot numeric(14,2) not null default 0,
  markup_percent numeric(8,4) not null default 0,
  sale_price_snapshot numeric(14,2) not null default 0,
  ipi_amount numeric(14,2) not null default 0,
  discount_amount numeric(14,2) not null default 0,
  display_order integer not null default 0
);

create table purchase_payments (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references purchases(id) on delete cascade,
  payment_date date not null,
  settlement_method settlement_method not null,
  amount_paid numeric(14,2) not null check (amount_paid >= 0),
  remaining_amount numeric(14,2) not null check (remaining_amount >= 0),
  notes text,
  created_at timestamptz not null default now()
);

create table accounts_receivable (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  customer_id bigint references customers(id),
  sale_id bigint references sales(id),
  cash_account_id bigint references cash_accounts(id),
  origin_type receivable_origin_type not null default 'manual',
  entry_date date not null default current_date,
  due_date date not null,
  description text not null,
  document_number text,
  principal_amount numeric(14,2) not null default 0,
  interest_rate numeric(8,4) not null default 0,
  amount_received numeric(14,2) not null default 0,
  interest_received numeric(14,2) not null default 0,
  discount_amount numeric(14,2) not null default 0,
  receipt_date date,
  is_open boolean not null default true,
  is_received boolean not null default false,
  notes text,
  legacy_code integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table accounts_payable (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  supplier_id bigint references suppliers(id),
  purchase_id bigint references purchases(id),
  cash_account_id bigint references cash_accounts(id),
  origin_type payable_origin_type not null default 'manual',
  entry_date date not null default current_date,
  due_date date not null,
  description text not null,
  document_number text,
  principal_amount numeric(14,2) not null default 0,
  interest_rate numeric(8,4) not null default 0,
  amount_paid numeric(14,2) not null default 0,
  interest_paid numeric(14,2) not null default 0,
  discount_amount numeric(14,2) not null default 0,
  payment_date date,
  is_open boolean not null default true,
  is_paid boolean not null default false,
  notes text,
  legacy_code integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table cash_entries (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  cash_account_id bigint not null references cash_accounts(id),
  entry_date date not null,
  description text not null,
  document_number text,
  entry_type cash_entry_type not null,
  amount numeric(14,2) not null check (amount >= 0),
  source_type text,
  source_id bigint,
  notes text,
  legacy_code integer,
  created_at timestamptz not null default now()
);

create table promotions (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  product_id bigint not null references products(id) on delete cascade,
  discount_amount numeric(14,2) not null default 0,
  promotional_price numeric(14,2) not null check (promotional_price >= 0),
  start_date date,
  end_date date,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table inventory_losses (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  product_id bigint not null references products(id),
  quantity numeric(14,3) not null check (quantity > 0),
  unit_price_snapshot numeric(14,2) not null default 0,
  loss_date date not null default current_date,
  reason loss_reason not null default 'other',
  notes text,
  legacy_code integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table inventory_movements (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  product_id bigint not null references products(id),
  movement_date date not null,
  movement_type text not null,
  quantity_delta numeric(14,3) not null,
  source_type text,
  source_id bigint,
  notes text,
  created_at timestamptz not null default now()
);

create table audit_events (
  id bigint generated by default as identity primary key,
  organization_id bigint references organizations(id) on delete cascade,
  actor_user_id bigint references app_users(id),
  entity_type text not null,
  entity_id bigint not null,
  action text not null,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index idx_customers_org_name on customers (organization_id, name);
create index idx_customers_org_document on customers (organization_id, document_number);
create unique index uq_customers_org_legacy_code
  on customers (organization_id, legacy_code)
  where legacy_code is not null;

create index idx_suppliers_org_trade_name on suppliers (organization_id, trade_name);
create index idx_suppliers_org_document on suppliers (organization_id, document_number);
create unique index uq_suppliers_org_legacy_code
  on suppliers (organization_id, legacy_code)
  where legacy_code is not null;

create index idx_products_org_name on products (organization_id, name);
create index idx_products_org_barcode on products (organization_id, barcode);
create index idx_products_org_group on products (organization_id, group_id);
create index idx_products_org_supplier on products (organization_id, supplier_id);
create unique index uq_products_org_legacy_code
  on products (organization_id, legacy_code)
  where legacy_code is not null;

create index idx_quotations_org_date on quotations (organization_id, quotation_date desc);
create index idx_quotations_org_customer on quotations (organization_id, customer_id);
create unique index uq_quotations_org_legacy_code
  on quotations (organization_id, legacy_code)
  where legacy_code is not null;

create index idx_quotation_items_quotation on quotation_items (quotation_id, display_order, id);

create index idx_sales_org_date on sales (organization_id, sale_date desc);
create index idx_sales_org_customer on sales (organization_id, customer_id);
create index idx_sales_org_vendor on sales (organization_id, vendor_id);
create unique index uq_sales_org_legacy_code
  on sales (organization_id, legacy_code)
  where legacy_code is not null;

create index idx_sale_items_sale on sale_items (sale_id, display_order, id);
create index idx_sale_items_product on sale_items (product_id);
create index idx_sale_receipts_sale_date on sale_receipts (sale_id, receipt_date, id);

create index idx_purchases_org_entry_date on purchases (organization_id, entry_date desc);
create index idx_purchases_org_supplier on purchases (organization_id, supplier_id);
create unique index uq_purchases_org_legacy_number
  on purchases (organization_id, legacy_number)
  where legacy_number is not null;

create index idx_purchase_items_purchase on purchase_items (purchase_id, display_order, id);
create index idx_purchase_payments_purchase_date on purchase_payments (purchase_id, payment_date, id);

create index idx_ar_org_due_date on accounts_receivable (organization_id, due_date);
create index idx_ar_org_customer on accounts_receivable (organization_id, customer_id);
create index idx_ar_org_open on accounts_receivable (organization_id, is_open, is_received, due_date);
create unique index uq_ar_org_legacy_code
  on accounts_receivable (organization_id, legacy_code)
  where legacy_code is not null;

create index idx_ap_org_due_date on accounts_payable (organization_id, due_date);
create index idx_ap_org_supplier on accounts_payable (organization_id, supplier_id);
create index idx_ap_org_open on accounts_payable (organization_id, is_open, is_paid, due_date);
create unique index uq_ap_org_legacy_code
  on accounts_payable (organization_id, legacy_code)
  where legacy_code is not null;

create index idx_cash_entries_org_date on cash_entries (organization_id, entry_date desc, id desc);
create index idx_cash_entries_org_account on cash_entries (organization_id, cash_account_id, entry_date desc);
create index idx_cash_entries_org_source on cash_entries (organization_id, source_type, source_id);
create unique index uq_cash_entries_org_legacy_code
  on cash_entries (organization_id, legacy_code)
  where legacy_code is not null;

create unique index uq_promotions_org_product_active
  on promotions (organization_id, product_id)
  where is_active = true;

create index idx_inventory_losses_org_date on inventory_losses (organization_id, loss_date desc);
create index idx_inventory_losses_org_product on inventory_losses (organization_id, product_id);
create unique index uq_inventory_losses_org_legacy_code
  on inventory_losses (organization_id, legacy_code)
  where legacy_code is not null;

create index idx_inventory_movements_org_date
  on inventory_movements (organization_id, movement_date desc, id desc);
create index idx_inventory_movements_org_product
  on inventory_movements (organization_id, product_id, movement_date desc);
create index idx_inventory_movements_org_source
  on inventory_movements (organization_id, source_type, source_id);

create index idx_audit_events_entity on audit_events (entity_type, entity_id, created_at desc);
create index idx_audit_events_org_created_at on audit_events (organization_id, created_at desc);

create trigger trg_organizations_set_updated_at
before update on organizations
for each row execute function set_updated_at();

create trigger trg_app_users_set_updated_at
before update on app_users
for each row execute function set_updated_at();

create trigger trg_cities_set_updated_at
before update on cities
for each row execute function set_updated_at();

create trigger trg_product_groups_set_updated_at
before update on product_groups
for each row execute function set_updated_at();

create trigger trg_units_set_updated_at
before update on units
for each row execute function set_updated_at();

create trigger trg_tax_rates_set_updated_at
before update on tax_rates
for each row execute function set_updated_at();

create trigger trg_cfop_codes_set_updated_at
before update on cfop_codes
for each row execute function set_updated_at();

create trigger trg_banks_set_updated_at
before update on banks
for each row execute function set_updated_at();

create trigger trg_cash_accounts_set_updated_at
before update on cash_accounts
for each row execute function set_updated_at();

create trigger trg_vendors_set_updated_at
before update on vendors
for each row execute function set_updated_at();

create trigger trg_customers_set_updated_at
before update on customers
for each row execute function set_updated_at();

create trigger trg_suppliers_set_updated_at
before update on suppliers
for each row execute function set_updated_at();

create trigger trg_products_set_updated_at
before update on products
for each row execute function set_updated_at();

create trigger trg_company_profiles_set_updated_at
before update on company_profiles
for each row execute function set_updated_at();

create trigger trg_business_settings_set_updated_at
before update on business_settings
for each row execute function set_updated_at();

create trigger trg_quotations_set_updated_at
before update on quotations
for each row execute function set_updated_at();

create trigger trg_sales_set_updated_at
before update on sales
for each row execute function set_updated_at();

create trigger trg_purchases_set_updated_at
before update on purchases
for each row execute function set_updated_at();

create trigger trg_accounts_receivable_set_updated_at
before update on accounts_receivable
for each row execute function set_updated_at();

create trigger trg_accounts_payable_set_updated_at
before update on accounts_payable
for each row execute function set_updated_at();

create trigger trg_promotions_set_updated_at
before update on promotions
for each row execute function set_updated_at();

create trigger trg_inventory_losses_set_updated_at
before update on inventory_losses
for each row execute function set_updated_at();

commit;
