program Poupador;

uses
  Forms, Interfaces,
  uClasses in 'Util\uClasses.pas',
  uNotifyEventDispatcher in 'Util\uNotifyEventDispatcher.pas',
  unDmPrincipal in 'Principal\unDmPrincipal.pas' {DmPrincipal: TDataModule},
  unPrincipal in 'Principal\unPrincipal.pas' {MainForm: TForm},
  ufmImprimeEtiq in 'Padrao\ufmImprimeEtiq.pas' {frmImprimeEtiq},
  unDialogoRelatorioPadrao in 'Padrao\unDialogoRelatorioPadrao.pas' {frmDialogoRelatorioPadrao},
  unModeloConsulta in 'Padrao\unModeloConsulta.pas' {frmModeloConsulta},
  unModeloEnvelope in 'Padrao\unModeloEnvelope.pas' {frmModeloEnvelope},
  unModeloRelatorio in 'Padrao\unModeloRelatorio.pas' {frmModeloRelatorio},
  unPadrao in 'Padrao\unPadrao.pas' {frmPadrao},
  unSimplePadrao in 'Padrao\unSimplePadrao.pas' {frmSimplePadrao},
  unAgenda in 'Utilitarios\unAgenda.pas' {frmAgenda},
  unConfiguraDuplicata in 'Utilitarios\unConfiguraDuplicata.pas' {frmConfiguraDuplicata},
  unDuplicatas in 'Utilitarios\unDuplicatas.pas' {frmDuplicatas},
  unEnvelopes in 'Utilitarios\unEnvelopes.pas' {frmEnvelopes},
  unImprimeRecibo in 'Utilitarios\unImprimeRecibo.pas' {frmImprimeRecibo},
  unPesqFone in 'Utilitarios\unPesqFone.pas' {frmPesqFone},
  unPromissoria in 'Utilitarios\unPromissoria.pas' {frmPromissoria},
  unRecibo in 'Utilitarios\unRecibo.pas' {frmRecibo},
  unPrevDuplicata in 'Utilitarios\Relatorios\Prev\unPrevDuplicata.pas' {frmPrevDuplicata},
  unPrevDuplicataSemForm in 'Utilitarios\Relatorios\Prev\unPrevDuplicataSemForm.pas' {frmPrevDuplicataSemForm},
  unPrevEnvelPerson in 'Utilitarios\Relatorios\Prev\unPrevEnvelPerson.pas' {frmPrevEnvelPerson},
  unPrevPromissoria in 'Utilitarios\Relatorios\Prev\unPrevPromissoria.pas' {frmPrevPromissoria},
  unPrevRecibo in 'Utilitarios\Relatorios\Prev\unPrevRecibo.pas' {frmPrevRecibo},
  unPrevRelAgenda in 'Utilitarios\Relatorios\Prev\unPrevRelAgenda.pas' {frmPrevRelAgenda},
  unRelatorioAgenda in 'Utilitarios\Relatorios\unRelatorioAgenda.pas' {frmRelatorioAgenda},
  unTrocaSenha in 'Sair\unTrocaSenha.pas' {frmTrocaSenha},
  unBaixaCheque in 'Movimentos\unBaixaCheque.pas' {frmBaixaCheque},
  unCaixa in 'Movimentos\unCaixa.pas' {frmCaixa},
  unCheque in 'Movimentos\unCheque.pas' {frmCheque},
  unCompNConc in 'Movimentos\unCompNConc.pas' {frmCompNaoConc},
  unContasPagar in 'Movimentos\unContasPagar.pas' {frmContasPagar},
  unContasPagas in 'Movimentos\unContasPagas.pas' {frmContasPagas},
  unContasReceber in 'Movimentos\unContasReceber.pas' {frmContasReceber},
  unContasRecebidas in 'Movimentos\unContasRecebidas.pas' {frmContasRecebidas},
  unCP in 'Movimentos\unCP.pas' {frmCP},
  unCR in 'Movimentos\unCR.pas' {frmCR},
  uNotificacoes in 'Principal\uNotificacoes.pas' {frmNotificacoes},
  unEtiquetaProduto in 'Movimentos\unEtiquetaProduto.pas' {frmEtiquetaProduto},
  unExclusaoCaixa in 'Movimentos\unExclusaoCaixa.pas' {frmExclusaoCaixa},
  unExclusaoProduto in 'Movimentos\unExclusaoProduto.pas' {frmExclusaoProduto},
  unImportaOrcam in 'Movimentos\unImportaOrcam.pas' {frmImportaOrcam},
  unLancCaixa in 'Movimentos\unLancCaixa.pas' {frmLancCaixa},
  unListagemPrecos in 'Movimentos\unListagemPrecos.pas' {frmListagemPrecos},
  unNotasFiscais in 'Movimentos\unNotasFiscais.pas' {frmNotasFiscais},
  unOrcamentos in 'Movimentos\unOrcamentos.pas' {frmOrcamentos},
  unPagamentoCheque in 'Movimentos\unPagamentoCheque.pas' {frmPagamentoCheque},
  unPagamentoCompra in 'Movimentos\unPagamentoCompra.pas' {frmPagamentoCompra},
  unPagamentoVenda in 'Movimentos\unPagamentoVenda.pas' {frmPagamentoVenda},
  unPagarMan in 'Movimentos\unPagarMan.pas' {frmPagarMan},
  unParcelaCompra in 'Movimentos\unParcelaCompra.pas' {frmParcelaCompra},
  unParcelaCPCR in 'Movimentos\unParcelaCPCR.pas' {frmParcelaCPCR},
  unParcelaVenda in 'Movimentos\unParcelaVenda.pas' {frmParcelaVenda},
  unPerda in 'Movimentos\unPerda.pas' {frmPerda},
  unProEstoqueMinimo in 'Movimentos\unProEstoqueMinimo.pas' {frmProEstoqueMinimo},
  unPromocao in 'Movimentos\unPromocao.pas' {frmPromocao},
  unReceberMan in 'Movimentos\unReceberMan.pas' {frmReceberMan},
  unSituacaoCliente in 'Movimentos\unSituacaoCliente.pas' {frmSituacaoCliente},
  unVendaNaoConc in 'Movimentos\unVendaNaoConc.pas' {frmVendaNaoConc},
  unVendas in 'Movimentos\unVendas.pas' {frmVendas},
  unPrevCaixaTodos in 'Movimentos\Relatorios\Prev\unPrevCaixaTodos.pas' {frmPrevCaixaTodos},
  unPrevCheque in 'Movimentos\Relatorios\Prev\unPrevCheque.pas' {frmPrevCheque},
  unPrevComissaoVenda in 'Movimentos\Relatorios\Prev\unPrevComissaoVenda.pas' {frmPrevComissaoVenda},
  unPrevCompras in 'Movimentos\Relatorios\Prev\unPrevCompras.pas' {frmPrevCompras},
  unPrevContasClientes in 'Movimentos\Relatorios\Prev\unPrevContasClientes.pas' {frmPrevContasClientes},
  unPrevContasPagar in 'Movimentos\Relatorios\Prev\unPrevContasPagar.pas' {frmPrevContasPagar},
  unPrevContasReceber in 'Movimentos\Relatorios\Prev\unPrevContasReceber.pas' {frmPrevContasReceber},
  unPrevCPAtrasados in 'Movimentos\Relatorios\Prev\unPrevCPAtrasados.pas' {frmRelatorioCPAtrasados},
  unPrevListaFaturamento in 'Movimentos\Relatorios\Prev\unPrevListaFaturamento.pas' {frmPrevListaFaturamento},
  unPrevNotaProm in 'Movimentos\Relatorios\Prev\unPrevNotaProm.pas' {frmPrevNotaProm},
  unPrevNotaVenda in 'Movimentos\Relatorios\Prev\unPrevNotaVenda.pas' {frmPrevNotaVenda},
  unPrevNotaVendaMatric in 'Movimentos\Relatorios\Prev\unPrevNotaVendaMatric.pas' {frmPrevNotaVendaMatric},
  unPrevOrcammento in 'Movimentos\Relatorios\Prev\unPrevOrcammento.pas' {frmPrevOrcamento},
  unPrevPerda in 'Movimentos\Relatorios\Prev\unPrevPerda.pas' {frmPrevPerda},
  unPrevPromocao in 'Movimentos\Relatorios\Prev\unPrevPromocao.pas' {frmPrevPromocao},
  unPrevRelCaixa in 'Movimentos\Relatorios\Prev\unPrevRelCaixa.pas' {frmPrevRelCaixa},
  unPrevRelCRAtrasadas in 'Movimentos\Relatorios\Prev\unPrevRelCRAtrasadas.pas' {frmPrevRelCRAtrasadas},
  unPrevVendas in 'Movimentos\Relatorios\Prev\unPrevVendas.pas' {frmPrevVendas},
  unRelatorioBobinaOrcam in 'Movimentos\Relatorios\unRelatorioBobinaOrcam.pas' {frmRelatorioBobinaOrcam},
  unRelatorioBobinaVenda in 'Movimentos\Relatorios\unRelatorioBobinaVenda.pas' {frmRelatorioBobinaVenda},
  unRelatorioCaixaContaCaixa in 'Movimentos\Relatorios\unRelatorioCaixaContaCaixa.pas' {frmRelatorioCaixaContaCaixa},
  unRelatorioCaixaMensal in 'Movimentos\Relatorios\unRelatorioCaixaMensal.pas' {frmRelatorioCaixaMensal},
  unRelatorioComissaoVenda in 'Movimentos\Relatorios\unRelatorioComissaoVenda.pas' {frmRelatorioComissaoVenda},
  unRelatorioCompraData in 'Movimentos\Relatorios\unRelatorioCompraData.pas' {frmRelatorioCompraData},
  unRelatorioCompraFornecedor in 'Movimentos\Relatorios\unRelatorioCompraFornecedor.pas' {frmRelatorioCompraFornecedor},
  unRelatorioCPData in 'Movimentos\Relatorios\unRelatorioCPData.pas' {frmRelatorioCPData},
  unRelatorioCPFornecedor in 'Movimentos\Relatorios\unRelatorioCPFornecedor.pas' {frmRelatorioCPFornecedor},
  unRelatorioCRAtraso in 'Movimentos\Relatorios\unRelatorioCRAtraso.pas' {frmRelatorioCRAtraso},
  unRelatorioCRCliente in 'Movimentos\Relatorios\unRelatorioCRCliente.pas' {frmRelatorioCRCliente},
  unRelatorioCRData in 'Movimentos\Relatorios\unRelatorioCRData.pas' {frmRelatorioCRData},
  unRelatorioFaturamento in 'Movimentos\Relatorios\unRelatorioFaturamento.pas' {frmRelatorioFaturamento},
  unRelatorioFluxoCaixa in 'Movimentos\Relatorios\unRelatorioFluxoCaixa.pas' {frmRelatorioFluxoCaixa},
  unRelatorioOrcamentoData in 'Movimentos\Relatorios\unRelatorioOrcamentoData.pas' {frmRelatorioOrcamentoData},
  unRelatorioVendaCliente in 'Movimentos\Relatorios\unRelatorioVendaCliente.pas' {frmRelatorioVendaCliente},
  ufmUsuarioItemMenu in 'Configuracoes\ufmUsuarioItemMenu.pas' {frmUsuarioItemMenu},
  unAliquota in 'Configuracoes\unAliquota.pas' {frmAliquota},
  unBanco in 'Configuracoes\unBanco.pas' {frmBanco},
  unCadastroCaixa in 'Configuracoes\unCadastroCaixa.pas' {frmCadastroCaixa},
  unCadastroCFOP in 'Configuracoes\unCadastroCFOP.pas' {frmCadastroCFOP},
  unCadastroCidade in 'Configuracoes\unCadastroCidade.pas' {frmCadastroCidade},
  unCadastroGrupo in 'Configuracoes\unCadastroGrupo.pas' {frmCadastroGrupo},
  unCadastroUnidade in 'Configuracoes\unCadastroUnidade.pas' {frmCadastroUnidade},
  unConfigNota in 'Configuracoes\unConfigNota.pas' {frmConfigNota},
  unConfigNotaMan in 'Configuracoes\unConfigNotaMan.pas' {frmConfigNotaMan},
  unConfiguracao in 'Configuracoes\unConfiguracao.pas' {frmConfiguracao},
  unConfiguracaoGlobal in 'Configuracoes\unConfiguracaoGlobal.pas' {frmConfigGlobal},
  unDadosEmpresa in 'Configuracoes\unDadosEmpresa.pas' {frmDadosEmpresa},
  unEtiqueta in 'Configuracoes\unEtiqueta.pas' {frmEtiqueta},
  unPerfilPermissao in 'Configuracoes\unPerfilPermissao.pas' {frmPerfilPermissao},
  unTrocaSenhaCaixa in 'Configuracoes\unTrocaSenhaCaixa.pas' {frmSenhaCaixa},
  unTrocaSenhaEstoque in 'Configuracoes\unTrocaSenhaEstoque.pas' {frmSenhaEstoque},
  unVendedor in 'Configuracoes\unVendedor.pas' {frmVendedor},
  unAcesso in 'Comuns\unAcesso.pas' {frmAcesso},
  unFoto in 'Comuns\unFoto.pas' {frmFoto},
  unSelecionaCaixa in 'Comuns\unSelecionaCaixa.pas' {frmSelecionaCaixa},
  unCliente in 'Cadastros\unCliente.pas' {frmCliente},
  unFornecedor in 'Cadastros\unFornecedor.pas' {frmFornecedor},
  unListagemProdutos in 'Cadastros\unListagemProdutos.pas' {frmListagemProdutos},
  unProduto in 'Cadastros\unProduto.pas' {frmProduto},
  unPrevClienteAniver in 'Cadastros\Relatorios\Prev\unPrevClienteAniver.pas' {frmPrevClientesAniver},
  unPrevEnvelopeClientes in 'Cadastros\Relatorios\Prev\unPrevEnvelopeClientes.pas' {frmPrevEnvelopeCliente},
  unPrevEtiquetaCliente in 'Cadastros\Relatorios\Prev\unPrevEtiquetaCliente.pas' {frmPrevEtiquetaCliente},
  unPrevEtiquetaProduto in 'Cadastros\Relatorios\Prev\unPrevEtiquetaProduto.pas' {frmPrevEtiquetaProduto},
  unPrevListagemClientes in 'Cadastros\Relatorios\Prev\unPrevListagemClientes.pas' {frmPrevListagemClientes},
  unPrevProdutoEstoque in 'Cadastros\Relatorios\Prev\unPrevProdutoEstoque.pas' {frmPrevProdutoEstoque},
  unPrevProdutoGrupo in 'Cadastros\Relatorios\Prev\unPrevProdutoGrupo.pas' {frmPrevProdutoGrupo},
  unPrevProdutosVencimento in 'Cadastros\Relatorios\Prev\unPrevProdutosVencimento.pas' {frmPrevProdutosVencimento},
  unPrevRelFornData in 'Cadastros\Relatorios\Prev\unPrevRelFornData.pas' {frmPrevRelFornData},
  unRelatorioAniversarioCliente in 'Cadastros\Relatorios\unRelatorioAniversarioCliente.pas' {frmRelatorioAniversarioCliente},
  unRelatorioClienteCidade in 'Cadastros\Relatorios\unRelatorioClienteCidade.pas' {frmRelatorioClienteCidade},
  unRelatorioClienteData in 'Cadastros\Relatorios\unRelatorioClienteData.pas' {frmRelatorioClienteData},
  unRelatorioEtiquetaCliente in 'Cadastros\Relatorios\unRelatorioEtiquetaCliente.pas' {frmRelatorioEtiquetaCliente},
  unRelatorioFornecedorCidade in 'Cadastros\Relatorios\unRelatorioFornecedorCidade.pas' {frmRelatorioFornecedorCidade},
  unRelatorioFornecedorData in 'Cadastros\Relatorios\unRelatorioFornecedorData.pas' {frmRelatorioFornecedorData},
  unRelatorioListaPrecos in 'Cadastros\Relatorios\unRelatorioListaPrecos.pas' {frmRelatorioListaPrecos},
  unRelatorioNovoAlterado in 'Cadastros\Relatorios\unRelatorioNovoAlterado.pas' {frmRelatorioNovoAlterado},
  unRelatorioProdutoEstMinForn in 'Cadastros\Relatorios\unRelatorioProdutoEstMinForn.pas' {frmRelatorioProdutoEstMinForn},
  unRelatorioProdutoGrupo in 'Cadastros\Relatorios\unRelatorioProdutoGrupo.pas' {frmRelatorioProdutoGrupo},
  unRelatorioProdutosEstoque in 'Cadastros\Relatorios\unRelatorioProdutosEstoque.pas' {frmRelatorioProdutosEstoque},
  unRelatorioProdutoVencimento in 'Cadastros\Relatorios\unRelatorioProdutoVencimento.pas' {frmRelatorioProdutoVencimento},
  unSobre in 'Ajuda\unSobre.pas' {frmSobre},
  uDmPesquisar in 'Padrao\uDmPesquisar.pas' {DmPesquisar: TDataModule},
  udmGeralBase in 'Padrao\udmGeralBase.pas' {dmGeralBase: TDataModule},
  udmAcesso in 'Comuns\Dm\udmAcesso.pas' {dmAcesso: TDataModule},
  unPrevRelCFOPs in 'Configuracoes\Relatorios\unPrevRelCFOPs.pas' {frmPrevRelCFOPs},
  udmBase in 'Padrao\udmBase.pas' {dmBase: TDataModule},
  uDBXConnectionParams in 'Util\uDBXConnectionParams.pas',
  uUtilFncs in 'Util\uUtilFncs.pas',
  ConstPadrao in 'Util\ConstPadrao.pas',
  Funcoes in 'Util\Funcoes.pas',
  VarGlobal in 'Util\VarGlobal.pas',
  DBXUtils in 'Util\DBXUtils.pas',
  ImgUtils in 'Util\ImgUtils.pas',
  uDatabaseUtils in 'Util\uDatabaseUtils.pas',
  crypto in 'Util\crypto.pas',
  ClassesGerador in 'Util\ClassesGerador.pas',
  uConfiguraRelatorio in 'Util\uConfiguraRelatorio.pas',
  Extensos in 'Util\Extensos.pas',
  uCheque in 'Util\uCheque.pas',
  uClassesMenu in 'Util\uClassesMenu.pas',
  udmCliente in 'Cadastros\Datamodule\udmCliente.pas' {dmCliente: TDataModule},
  udmDuplicatas in 'Utilitarios\Datamodule\udmDuplicatas.pas' {dmDuplicatas: TDataModule},
  uMenuActions in 'Principal\Classes\uMenuActions.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.Run;
end.
